### ISSUE TITLE
Move cursor to corner of focused window

### ISSUE THREAD

**Issue by japrogramer** [vaxerski/Hyprland#101]
**Describe in detail your idea.**

I noticed that when movefocus is called the cursor moves to the center of the focused window.
In xmonad there is a way to move the cursor to the corners of the screen by pressing a key combination

Here is one way I used the feature when I was using xmonad
https://github.com/japrogramer/xmonad-hs/blob/master/xmonad.hs#L156

**Comment by vaxerski** [comment]
and whats the idea here?

**Comment by japrogramer** [comment]
To move the cursor out of the way without lifting the hands from the keyboard

**Comment by vaxerski** [comment]
ok

**Comment by vaxerski** [comment]
added in e924cd95fde26bf776951800a595662bba0b9326
