### ISSUE TITLE
Dispatcher to make all windows (and future spawned windows) on a workspace tiled/pseudo/float

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#104]
**Describe in detail your idea.**

As the title says, a dispatcher to make all windows (and future spawned windows) on a workspace tiled/pseudo/float would be very useful.

ex.

```
bind=SUPER,I,alltile,
bind=SUPER,O,allfloat,
bind=SUPER,P,allpseudo,

```

**Comment by vaxerski** [comment]
I am guessing the "alltile" would be like it works rn? true alltile with xwayland would be a bad idea.

**Comment by ThatOneCalculator** [comment]
> I am guessing the "alltile" would be like it works rn? 

Yep

**Comment by vaxerski** [comment]
added in 795504dad01e7d738f768315767523270e59ab54

**Comment by ThatOneCalculator** [comment]
:(

![image](https://user-images.githubusercontent.com/44733677/170564868-9b225047-1e7c-434c-9fd9-6944eea96b44.png)

**Comment by vaxerski** [comment]
[https://github.com/vaxerski/Hyprland/wiki/Advanced-config#workspaceopt](https://github.com/vaxerski/Hyprland/wiki/Advanced-config#workspaceopt)

**Comment by ThatOneCalculator** [comment]
Ah gotcha. Is there one for `alltile` or default?

**Comment by vaxerski** [comment]
`alltile` is basically `allfloat` turned off.

allfloat and allpseudo are toggleable 0/1 options, the dispatcher switches them.

**Comment by ThatOneCalculator** [comment]
awesome ty, this is now officially the best WM ever to exist (it was already amazing but now it makes it infinitely better than bspwm)

**Comment by vaxerski** [comment]
its not a wm, but thanks for the kind words qt <3
