### ISSUE TITLE
SUPERSHIFT bind doesn't work with Number KEY

### ISSUE THREAD

**Issue by taylor85345** [vaxerski/Hyprland#11]
**Describe the bug**
Binding a number key (0-9) with the SUPERSHIFT modifier does not work. The keybind remains unresponsive. This key combination is a fairly common default for moving windows between workspaces in other WM's, so it's non-functionality may be confusing to some users. 

For example, the following config block does not work as intended:

```
bind=SUPERSHIFT,1,movetoworkspace,1
bind=SUPERSHIFT,2,movetoworkspace,2
bind=SUPERSHIFT,3,movetoworkspace,3
bind=SUPERSHIFT,4,movetoworkspace,4
bind=SUPERSHIFT,5,movetoworkspace,5
bind=SUPERSHIFT,6,movetoworkspace,6
bind=SUPERSHIFT,7,movetoworkspace,7
bind=SUPERSHIFT,8,movetoworkspace,8
bind=SUPERSHIFT,9,movetoworkspace,9
bind=SUPERSHIFT,0,movetoworkspace,10
```

The problem appears to be that the holding SHIFT+(0-9) returns the special character for that number key, rather than the actual number, and hyprland doesn't associate the special character keypress with the matching number key (sorry if I'm explaining this poorly, not sure of the proper terminology). An effective workaround is to specify the special character key, rather than the number key, in the config. For example, the following config block currently achieves the desired results for SUPERSHIFT+(0-9)

```
bind=SUPERSHIFT,exclam,movetoworkspace,1
bind=SUPERSHIFT,at,movetoworkspace,2
bind=SUPERSHIFT,numbersign,movetoworkspace,3
bind=SUPERSHIFT,dollar,movetoworkspace,4
bind=SUPERSHIFT,percent,movetoworkspace,5
bind=SUPERSHIFT,asciicircum,movetoworkspace,6
bind=SUPERSHIFT,ampersand,movetoworkspace,7
bind=SUPERSHIFT,asterisk,movetoworkspace,8
bind=SUPERSHIFT,parenleft,movetoworkspace,9
bind=SUPERSHIFT,parenright,movetoworkspace,10
```

Ideally I think these special character keys should be associated with their matched number keys so that the first config block would achieve the same results as the second. However, if this behavior is intended or otherwise non-trivial to correct, I think this should at least be documented in the wiki to alleviate some confusion.

**Comment by vaxerski** [comment]
I do know about that and I even mention it [here](https://github.com/vaxerski/Hyprland/blob/main/src/managers/KeybindManager.cpp#L43)

But I have no idea how to fix that.

**Comment by vaxerski** [comment]
Mentioned it in the wiki. It's not trivial to fix.

I will also upgrade hyprctl with time and probably add an option to log the keysyms.

**Comment by vaxerski** [comment]
I'll close this for now - it's mentioned in the wiki, and I have no intentions of seeking a way to "fix" that for the time being.
