### ISSUE TITLE
Features: `Animations`: startup, shutdown, closing windows. `Rules`: rounded corners

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#113]
Good day to you!

Suggestion for animation for :
* closing windows (similar  to opening windows rules)
* animation on startup and shutdown (wrapper around killing process?) `Hyprland`

 sugestion for applying rounded corners by rules 
```bash
windowrule=rounded corner 0, util
```

suggestion for defining rounded corner value for each corner, so:
```bash
decoration={
# rounding=<TL> <TR> <BR> <BL> 
rounding=10 10 0 0
}
```

**Comment by vaxerski** [comment]
Startup/shutdown animations are:

- pretty pointless
- will hinder productivity
- startup animations aren't really good, as the compositor doesn't really know when all displays are "ready"

Rounding:

rules: ok. Separate corners, not planned right now, would require a bit of changes to the texture shader, and I am unsure of the performance impact. Will test some day.

**Comment by fedoranvar** [comment]
what about window closing animation?

**Comment by vaxerski** [comment]
ah yeah forgot. Yes it will be implemented.

**Comment by vaxerski** [comment]
added a rounding rule in 7f1f14fe85f53fcf12849632d3f003f00cca7578

**Comment by vaxerski** [comment]
added closing anims in 15553804d644fd66c52d270c729c5250b06ee9e4

**Comment by fedoranvar** [comment]
closins animations works

but  rounding doesn't work for me with this settings:

```bash
windowrule=rounding 0, util
...
decoration {
    rounding=10
}
```

**Comment by vaxerski** [comment]
works for me. I think the issue is that you have a dangling space there.
```
windowrule=rounding 0,util
```

**Comment by fedoranvar** [comment]
you're right! that's all works good.

closing
