### ISSUE TITLE
Blur is no longer blurry

### ISSUE THREAD

**Issue by TheLastTeapot** [vaxerski/Hyprland#115]
Instead it is cloudy, and changing the blur amount doesn't change anything
I don't know if this is an intentional change, but if it is, this is a feature request for a "change it back" option

[hyprland.log](https://github.com/vaxerski/Hyprland/files/8791423/hyprland.log)

**Comment by vaxerski** [comment]
![20220528_18h34m40s_grim](https://user-images.githubusercontent.com/43317083/170834394-99acc683-d4a6-460f-a9a3-7068d21cd7d6.png)

No clue what you're talking about. Maybe if you did follow the issue template and given me your config I'd be able to identify your issue better.

**Comment by TheLastTeapot** [comment]
[hyprland.txt](https://github.com/vaxerski/Hyprland/files/8791491/hyprland.txt)
I don't actually have my config in .txt format but I had to attach a clone for github

**Comment by TheLastTeapot** [comment]
I don't know if this is relevant but I just reinstalled arch to fix another issue

**Comment by vaxerski** [comment]
Your window's opacity makes the blur translucent too.

**Comment by TheLastTeapot** [comment]
but the problem is not how translucent it is, it is how blurry it is. I can still see distinct details of my background even under heavy blur. (like 30 size, 4 passes)

**Comment by vaxerski** [comment]
Yes, because the blur layer is translucent too.

**Comment by TheLastTeapot** [comment]
it's very different than it used to be, even with the exact same config

**Comment by vaxerski** [comment]
Yes, it has changed over the commits. I can make an option to bring it back. I remember there was some issue with it though, can't remember what.

**Comment by TheLastTeapot** [comment]
I see, thanks!

**Comment by TheLastTeapot** [comment]
This must mean something was preventing Hyprland from updating before I reinstalled arch, because it wasn't like this when I updated Hyprland right before I reinstalled arch.

**Comment by TheLastTeapot** [comment]
Unless that specific commit happened in the hour I was reinstalling

**Comment by TheLastTeapot** [comment]
However, what might work better than an option to bring the old blur back, if that is the problem, would be an option to change the blur layer transparency

**Comment by vaxerski** [comment]
No, it was like 2 weeks ago. Added `decoration:blur_ignore_opacity`.
