### ISSUE TITLE
Feature: Tabbed windows navigation

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#116]
Good day to you!

Right now there is only one-way (forward) for focusing window in tabs.
Suggestions:

* to add backward motion
or 
* maybe some `overview` keymap for tabbed windows, that will allow overview and jump window, similar to tmux (pic below)

![image](https://user-images.githubusercontent.com/52028706/170835555-78c853ae-6a45-42c8-954c-36a060852039.png)

**Comment by vaxerski** [comment]
Backwards motion - ok.

Overview - no, the renderer is not really made for that.

**Comment by vaxerski** [comment]
Added in b1b24cb21a36713aa7c8c0d39464504c97423139

```
bind=SUPER,SOMETHING,changegroupactive,f
```
`f` -> forwards
`b` -> backwards

**Comment by fedoranvar** [comment]
works good.

Thank you!
