### ISSUE TITLE
Feature: maximize window

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#118]
Good day to you!

Suggestion: 
ability for keymapping to maximize window (to keep outer gaps)

Thank you!

**Comment by vaxerski** [comment]
what? fullscreen exists

**Comment by fedoranvar** [comment]
fullscreen:
* takes whole output 
* some apps (e.g. chromium) enters in fullscreen-mode, where it's hide tabs

maximize:
* takes only workarea, so outer gaps stays visible
* apps don't enter in fullscreen mode

**Comment by vaxerski** [comment]
ok

**Comment by vaxerski** [comment]
added, use
```
bind=MOD,KEY,fullscreen,1
```
for maximizing, 0 for the old style.

**Comment by fedoranvar** [comment]
@vaxerski 

almost good, but still it sends application to fullscreen mode, e.g. `Brave`
![image](https://user-images.githubusercontent.com/52028706/170929824-b26e232b-e573-46f6-bedd-18c66a2383b6.png)

after entering fullscreen it hides tab-bar:

![image](https://user-images.githubusercontent.com/52028706/170930306-926cdd1f-66db-4539-ad02-6c75081530c0.png)

**Comment by vaxerski** [comment]
ah shoot oops

**Comment by vaxerski** [comment]
fixed

**Comment by fedoranvar** [comment]
it works good.

thank you!
