### ISSUE TITLE
hyprland crashes on movetoworkspace,-1

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#124]
**Describe the bug**
in my config file:
bind=SUPERALTCTRL,left,movetoworkspace,-1
When I ask for this action (movetoworkspace,-1, which in my understanding will move the window to the previous workspace, as -1 should be interpreted as relative as per https://github.com/vaxerski/Hyprland/wiki/Advanced-config), this crashes hyprland. This is totally reproducible.

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8798176/hyprland.log)
[hyprland.core.txt](https://github.com/vaxerski/Hyprland/files/8798181/hyprland.core.txt)

**Comment by vaxerski** [comment]
fixed in 7167be9c482760c81f70153f4457f60cca4e9c80

for future bug reports, do NOT submit coredumps from the AUR package. Compile manually and then send the coredump.

Cheers

**Comment by frigaut** [comment]
Thanks! will do for coredumps.

**Comment by frigaut** [comment]
I got it to work without crashing once but now it crashes again.
Removed the aur package and built from source.
```bash
$ git log --pretty=format:'%h' -n 5
b1c11f3
da63503
7167be9
e81790f
edf57c5
```

```bash
$ hyprctl version
Hyprland, built from branch  at commit dirty ().
flags: (if any)
```

new log and coredump attached.
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8798534/hyprland.log)
[hyprland.core.txt](https://github.com/vaxerski/Hyprland/files/8798535/hyprland.core.txt)

**Comment by frigaut** [comment]
Note that 
```bash
hyprctl dispatch movetoworkspace +1
```
now also crashes... ;-)

**Comment by vaxerski** [comment]
sowwy, fixed uwu

also how tf is your version empty

**Comment by frigaut** [comment]
I've got no idea why hyprctl version reports an empty version. 
I have built it from the cloned hyprland repo (the hyprctl from the aur repo use to give me a version).
From the TTY, I just 
```bash
cd packages/Hyprland
git pull
sudo make install
```
then start hyprland from TTY. Anything I forgot?

**Comment by vaxerski** [comment]
nope, seems good to me. Idk, maybe something off with sudo. Oh well, minor.
