### ISSUE TITLE
hyprland crashes when disconnecting external HDMI monitor

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#125]
**Describe the bug**

- Connect an external HDMI monitor (configured in hyprland.conf)
- Start hyprland. Both internal (laptop) and external monitors are on and have workspaces
- Disconnect HDMI monitor
- hyprland crashes
(note that hot **connecting** works fine)

Expected behaviour: Hyprland handles monitor disconnection by (not crashing and) redirecting all current workspaces to remaining monitor.

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

*Please do NOT attach coredumps from any packaged version of Hyprland (AUR, etc.). Compile manually, and THEN attach a coredump of that.*
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8799020/hyprland.log)
[hyprland.core.txt](https://github.com/vaxerski/Hyprland/files/8799022/hyprland.core.txt)

**Comment by vaxerski** [comment]
should be fixed with c44c79abb269da36b68d0524f45aa4c0b92dedca

please verify though.

**Comment by vaxerski** [comment]
added
