### ISSUE TITLE
Implement moveCurrentWorkspaceToMonitor,(number|next|previous)

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#126]
**Describe in detail your idea.**

As it says above. Multi-monitor support is where tilling WM shine. Having the ability of move entire workspaces around from monitor to monitor is a core feature of multi-monitor support.

Detail: 
moveCurrentWorkspaceToMonitor,(number|next|previous) would obviously move an entire workspace to a different monitor specified by its number, or previous or next

There's actually probably two variants of this that could benefit from being implemented:
- moveCurrentWorkspaceToMonitor,monitor_number (or previous or next)
- moveWorkspaceToMonitor,Workspace_number,Monitor_number (or previous or next)

:-)

**Comment by vaxerski** [comment]
the obvious question this adds is: what if we are moving the only workspace on monitor X away? Hyprland does not allow for a monitor to NOT have an active workspace. I guess it'd just open the next valid id

**Comment by vaxerski** [comment]
next/prev is stupid. It will use directions instead. (l,r,u,d)

**Comment by frigaut** [comment]
sounds perfect!

Additional question: you refer to a discord hyprland server in the FAQ, but I can't find it. I wanted to contribute to the wiki FAQ but I can't clone hyprdland.wiki.git:
```bash
$ git clone https://github.com/frigaut/Hyprland.wiki.git
Cloning into 'Hyprland.wiki'...
fatal: remote error: access denied or repository not exported: /c/nw/c2/eb/17/441054348/498002363.wiki.git
```

**Comment by vaxerski** [comment]
the discord server link is a big button in the readme.

**Comment by frigaut** [comment]
duh

**Comment by vaxerski** [comment]
done

**Comment by frigaut** [comment]
hum...
```bash
$ git log --pretty=format:'%h' -n 5
c44c79a
1e096f6
b1c11f3
da63503
7167be9
┬─[frigaut@poliahu:~/p/Hyprland]─[20:24:50]─[G:main=]
╰─>$ hyprctl dispatch movecurrentworkspacetomonitor 0
Invalid dispatcher⏎                                                             ┬─[frigaut@poliahu:~/p/Hyprland]─[20:25:00]─[G:main=]
╰─>$
```

**Comment by frigaut** [comment]
wait, not the right commit.

**Comment by frigaut** [comment]
nothing to pull

**Comment by frigaut** [comment]
forget it, I was pulling from my forked repo of Hyprland

**Comment by frigaut** [comment]
That's beautiful!

First pass of tests: it works wonderfully. 

However, there seems to be a problem with waybar: the workspace does move, but on waybar it stays associated with the old monitor. I have restarted waybar and this does not change. I can explain further if needed:
- I have create workspaces 1,2 on monitor 0, and workspace 3,4 on monitor 1
  - waybar lists them ok
- if I move ws 1 on monitor 1, waybar still lists 1,2 on monitor 0, and workspace 3,4 on monitor 1, although a hyprctl workspaces list the correct thing. Any hint?

**Comment by vaxerski** [comment]
sec

**Comment by vaxerski** [comment]
check now

**Comment by frigaut** [comment]
yeah, you seem to have fixed it. testing more.

**Comment by frigaut** [comment]
syntax to moveworkspacetomonitor?
```bash
hyprctl dispatch moveworkspacetomonitor 3,d
```
reports ok but nothing happens.

**Comment by frigaut** [comment]
OMG, this is super nice. the effects when moving workspaces from monitor to monitor, everything changing so smooth...

**Comment by frigaut** [comment]
Bottom line: 
- movecurrentworkspacetomonitor: I have tested both the `hyprctl dispatch` and the binds, and all work well. I can't make it fails or crash.
- moveworkspacetomonitor: bind doesn't make sense. can't test `hyprctl dispatch` - awaiting clarification on syntax (trying to second guess your code didn't bring me much clarity)

**Comment by vaxerski** [comment]
ah there is an example in the wiki, it isn't separated by a comma but by a space

```
bind=SUPER,G,moveworkspacetomonitor,4 0
```
will move workspace 4 to monitor 0

**Comment by vaxerski** [comment]
oh wait I'm an idiot

```
hyprctl dispatch moveworkspacetomonitor "4 0"
```

**Comment by frigaut** [comment]
I am the idiot. I did not reload the wiki.
Everything checks out!

**Comment by frigaut** [comment]
probly should use discord for testing runs like this :-)

**Comment by frigaut** [comment]
I have just one final enhancement proposal to improve the workflow that I will submit tomorrow (just traveled yesterday from Australia to France and I am dead tired). 
I have a couple of additions I could make to the wiki FAQ, best would be through pull requests that you could accept or reject. But the wiki is not clonable?

**Comment by vaxerski** [comment]
wikis on github aren't clonable, and you can't submit PRs. I'd recommend to just plop the proposed changes on discord and I'll add them
