### ISSUE TITLE
Crash with latest version of wlroots

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#127]
**Describe the bug**

Crashes when doing almost anything, like opening/closing windows, switching workspaces, etc. All I can do is open a terminal. 

**Images/videos/anything that would help**

![PXL_20220530_231525818.MP.jpg](https://user-images.githubusercontent.com/44733677/171067172-10da99c9-ffd2-456d-b43d-2dd770b142cf.jpg)

~~This happens on the from source and aur versions. I can't even open Firefox to attach a coredump or log, I'm writing this from my phone.~~

Update: I was able to get the logs on a pastebin via the tty

/tmp/hypr/hyprland.log: https://zer0b.in/YpmyECP2

coredump: 
https://zer0b.in/UHNklTKW

**Comment by taylor85345** [comment]
I reported an identical issue this morning on discord. It seems to crash any time a window frame is closed, including seemingly innocuous things like dismissing notifications or interacting with right-click menus.

@ThatOneCalculator are you on Nvidia graphics as well, out of curiosity? I've been assuming that was the culprit, but I'd love to be wrong.

**Comment by vaxerski** [comment]
it's probably wlroots if multiple people are reporting it.

I have just woken up, give me an hour and I'll try to fix the wlroots issues once and for all

**Comment by ThatOneCalculator** [comment]
> @ThatOneCalculator are you on Nvidia graphics as well, out of curiosity? I've been assuming that was the culprit, but I'd love to be wrong

Nope, if you look at the coredump you'll see I'm on an AMD 6700XT

**Comment by ThatOneCalculator** [comment]
> it's probably wlroots if multiple people are reporting it.
> 
> I have just woken up, give me an hour and I'll try to fix the wlroots issues once and for all

Tysm ❤️❤️❤️

Is there gonna be a time where Hyprland can depend on a stable-ish version of wlroots?

**Comment by vaxerski** [comment]
No. I am planning on using wlroots-git forever, but I am working on a system where I choose when to update wlroots, and it's bundled with hyprland. This would also fix the "I have wlroots for sway, how do i use wlroots-git for hyprland???" problems

**Comment by vaxerski** [comment]
@ThatOneCalculator it's now fixed. Please note you probably have to update both the AUR package and the standard one to work with the new bundling.

I've updated the wiki, the manual building and releases section should now reflect the correct steps to install.

Cheers.

**Comment by ThatOneCalculator** [comment]
@vaxerski Did the build process change? I get this when using the current PKGBUILD (which is literally just `make all`)

**Comment by vaxerski** [comment]
NO DONT YOU'LL MESS UP THE COMMIT

submodules are pinned to a commit for a reason, do NOT update it

**Comment by ThatOneCalculator** [comment]
OOOH sowwy

**Comment by ThatOneCalculator** [comment]
idk what to do tbh, is there a version of `git submodule update --init` that doesnt update the thingies?

**Comment by vaxerski** [comment]
no clue, tryna find one rn

**Comment by vaxerski** [comment]
oh wait nvm,
```
git submodule init && git submodule update
```
seems to point to the correct commit. My bad. Check it before publishing though, it should be at `75d31509db8c28e8379fe9570118ef8c82284581`

**Comment by ThatOneCalculator** [comment]
Yea, it did.

**Comment by robbins** [comment]
> no, you need to `git clone --recursive` though

It seems like the Nix Flakes build also fails for this same reason, and I'm unable to find a submodules option for Flake inputs.
