### ISSUE TITLE
Focus next WS on monitor

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#129]
Last one for a while, I promise.

When using multiple monitors, one often wants to navigate the WS on the current monitor only, and keep the other monitor focused on the same WS. With the current implementation of "workspace,+1 | -1", I am going through all WS in order, and thus potentially changing the WS on the other monitor if I go through WS on it. Of course, I can use "workspace,N" directly, but for my workflow I am used to next/previous WS (which means I don't have to reach up to the number keys and think it over, arrow keys are a shorter reach).

This would be done by implementing a "focusNextWSonCurrentMonitor" (or prev). Of course, that would mean to keep a registry of what WS are on what monitor, but you probably have that already :-)

**Alternatively and probably a better idea** than a separate command, 
```bash
workspace,nextOnMonitor | prevOnMonitor
```
might be better.

An extension of this for a move:
```bash
movetoworkspace,nextOnMonitor | prevOnMonitor
```
would also be very useful

All this would not break the current behaviour, just add a very useful functionality.

**Comment by vaxerski** [comment]
Added. You can now use relative offsets with monitors by adding `m` before the offset, for example:

```
bind=SUPER,J,workspace,m+1
```
will switch to the next workspace on the current monitor. This will work with all dispatchers with the workspace parameter.
