### ISSUE TITLE
Workspaces in waybar don't work when using Ly GDM 

### ISSUE THREAD

**Issue by Vagahbond** [vaxerski/Hyprland#131]
**Describe the bug**
When logging in with [ly](https://github.com/fairyglade/ly), I have no workspace on my waybar, whereas I do when I launch Hyprland in TTY.

I obviously read the wiki and did add the flags to waybar and recompiled it myself. ;)

**Images/videos/anything that would help**
When logged in with ly:
![1653988944_grim](https://user-images.githubusercontent.com/56230065/171141375-c291bcc0-95e6-477e-bddc-9c919ecb6a88.png)

When logged in directly in TTY:
![1653988995_grim](https://user-images.githubusercontent.com/56230065/171141477-bfa2be1a-435d-42b9-b485-e71118d99d95.png)

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland (copy 1).log](https://github.com/vaxerski/Hyprland/files/8803898/hyprland.copy.1.log)

*Please do NOT attach coredumps from any packaged version of Hyprland (AUR, etc.). Compile manually, and THEN attach a coredump of that.*

**Comment by vaxerski** [comment]
1) you're using outdated hyprland.

2) it's an issue with ly then, no?
Login managers are *not* officially supported. If they work, cool. If they don't, unfortunate. I cannot possibly account for all login managers, and besides, if something doesn't work when using XYZ login manager, and does work without it, then it's their fault, not mine.

I've updated the wiki to mention ly having issues.

This is not for me to fix, this has to be reported to the ly devs for them to work on.

**Comment by vaxerski** [comment]
PS. If they insist it's not their fault, SDDM works flawlessly.

**Comment by Vagahbond** [comment]
Alright, thank you !
