### ISSUE TITLE
Touchpad Gestures

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#132]
It would be nice if we had touch gestures

**Comment by Vagahbond** [comment]
Do you mean on touchscreen or touchpad ? for touchpad gesture I personnaly use [this](https://github.com/bulletmark/libinput-gestures) and it works like a charm.

**Comment by vaxerski** [comment]
try using what @Vagahbond suggested, with `hyprctl`.

**Comment by godalming123** [comment]
Yes that would help new users. I would prefer 1:1 gesture (like fufexan said) but there are more important things to do
