### ISSUE TITLE
Add option to hide borders when 1 window is open

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#139]
I can only see mentions of the border property in the docs it does not specify that they're in general and does not show any way to hide the border if only 1 window is open. I assume this is'nt present but I don't know

**Comment by godalming123** [comment]
It looks cleaner

**Comment by vaxerski** [comment]
furthermore: the bash sockets and hyprctl API (configs) are developed more and more, so even on multimon it will be possible soon, probably.

**Comment by godalming123** [comment]
ok maybe I will fork later but for now this is a minor aesthetic feature
