### ISSUE TITLE
Issues with compiled releases

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#141]
- No hyprctl
- 0.2.1beta doesn't contain wlroots
![image](https://user-images.githubusercontent.com/44733677/171277791-c023dd35-f3d5-440c-b57f-6d73d2199264.png)

**Comment by vaxerski** [comment]
im an idiot lol sorz gonna push 0.2.2beta

**Comment by ThatOneCalculator** [comment]
# :suspect:

**Comment by ThatOneCalculator** [comment]
@vaxerski can't you use github actions to make releases for you

**Comment by vaxerski** [comment]
too lazy and idk how really lol anyways pushed
