### ISSUE TITLE
Setting wayland gui toolkit environment variables on startup

### ISSUE THREAD

**Issue by pranjlp** [vaxerski/Hyprland#150]
**Describe the bug**
I prefer starting wayland compositors using the following command to initialise a wayland session so that all apps are start as native wayland apps..  It works with sway and river. 
`env GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland,xcb Hyprland`

It doesn't work with Hyprland..

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

*Please do NOT attach coredumps from any packaged version of Hyprland (AUR, etc.). Compile manually, and THEN attach a coredump of that.*

**Comment by vaxerski** [comment]
I don't understand what is the problem or what you mean

**Comment by pranjlp** [comment]
@vaxerski  Edited the issue.. Removed the unnecessary confusing details. I am not able to set environment variables on Hyper using the command I mentioned above, which leads to all GTK and Qt apps to use Xwayland instead of native wayland

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/171393942-2356bd7a-1158-4114-90ac-76bfa59b705d.png)
these 2 are set by hyprland.

**Comment by pranjlp** [comment]
Well.. apparently there was some bug which allowed env to set environment variables... As of now.. it has stopped working for me. Closing this.
Leaving it here for systemd users.. to start a fresh login.. unsetting all system environment variables, use this
```
loginctl terminate-user [USER]
```
