### ISSUE TITLE
Scale animation fails for firefox

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#152]
**Describe the bug**

When I open a new terminal on the right Firefox does not play a scale animation as do all other windows.

**Comment by godalming123** [comment]
ok since you know the specefic's should you file an issue on mozilla ideas

**Comment by user451421541757324** [comment]
> it's a firefox issue, it doesn't use the wayland protocol correctly.

Do you know where I can track this bug? I can't find anything on Bugzilla.

**Comment by vaxerski** [comment]
doubt there is one. It's valid, but nonstandard. For some reason all browsers seem to do that.
