### ISSUE TITLE
Window rules improvements

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#153]
I would like to build a gtk4 app for wallpaper bar ...ETC but I cannot configure it's position and layer in gtk so could you improve the window-rules options:
1. layer option one of normal below or on top
2. (I don't need this but maybe for other users) an option to make windows part of the tiling space IE they aren't tiled over but you can still mouse-over them

**Comment by vaxerski** [comment]
> layer option one of normal below or on top

what?

> an option to make windows part of the tiling space IE they aren't tiled over but you can still mouse-over them

I don't understand, floating windows exist?

**Comment by godalming123** [comment]
I mean by the second option that if you have a bar hyprland will not tile windows over your bar so you can always see it. This might be doable with moniter reservations though.
And for a layer option I mean an option for wether the window will go above normal apps (so you can always see it), below normal apps (like a wallpaper window it never blocks any window from being visible), or normal IE treated as a normal window that can go above or below other windows depending on when they were placed

**Comment by vaxerski** [comment]
no. That's what the layersurface protocol is for and it's fully supported by Hyprland. Please use the protocol correctly and not rely on the compositor to include weird features. This is not Xorg.

**Comment by godalming123** [comment]
Do you have a link to any docs on this protocol?

**Comment by vaxerski** [comment]
[https://wayland.app/protocols/wlr-layer-shell-unstable-v1](https://wayland.app/protocols/wlr-layer-shell-unstable-v1)

You can also see the source code of simple apps that utilize it, for example [wofi](https://hg.sr.ht/~scoopta/wofi) or [swaybg](https://github.com/swaywm/swaybg)
