### ISSUE TITLE
Crashes when closing a window with multiple monitors connected

### ISSUE THREAD

**Issue by robbins** [vaxerski/Hyprland#154]
**Describe the bug**
When I hit Mod+C to close a window and have a second HDMI monitor connected, Hyprland crashes immediately.

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

*Please do NOT attach coredumps from any packaged version of Hyprland (AUR, etc.). Compile manually, and THEN attach a coredump of that.*

[crash_multi_monitor.txt](https://github.com/vaxerski/Hyprland/files/8819881/crash_multi_monitor.txt)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8819882/hyprland.log)

EDIT: It is now just crashing everytime I try and close a window, even with no external monitor connected.

I have only added this line to my config:
`monitor=eDP-1,1920x1080@144,0x0,1` and it seems to be the cause, as I then get crashes.

I can add `monitor=HDMI-A-1,1920x1080@60,0x0,1` to my config (and get mirrored displays) and do not get any crashes, as long as I don't have the above eDP line. However if I add any offset it crashes when closing windows as well.

**Comment by godalming123** [comment]
I think the defualt config quits Hyprland when you use mod + c could you post your config (in ~/.config/hypr/hyprland.conf)

**Comment by godalming123** [comment]
The default behavior does indeed close a window.

**Comment by godalming123** [comment]
I think it's something to do with your refresh rate have you tried using:
```
monitor=eDP-1,1920x1080@60,0x0,1
```
For me I have a laptop and moniter and can configure them to not mirrorby moving them EG:
``
monitor=,1920x1080@60,0x0,1 #hdmi moniter
monitor=eDP-1,1080x720@60,300x1080,1 #laptop screen notice the 300x1080 this moves it down so you do not get mirrord displays
``

**Comment by vaxerski** [comment]
you can also try to use the releases if you don't know how to compile properly.
