### ISSUE TITLE
Defining variables as the output to commands

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#156]
I have a program that dynamically changes my theme based on my wallpaper I can access the colors in this theme by running a command and assigning the output to a variable that I can then use but this is not currently an option.
The syntax could look like this:
```
$myVar = (command)
```

**Comment by vaxerski** [comment]
```
source=~/colors.conf
```

colors.conf:
```
$myCol1=0xsomecol
$myCol2=0xsomecol
```

changeColors.sh:
```
#!/bin/sh

myCol1 = $(somecommand)
myCol2 = $(somecommand)

printf "\$myCol1=$myCol1\n\$myCol2 = $myCol2" > ~/colors.conf
```

knowing bash is useful.
