### ISSUE TITLE
Small issue in workspace numbering/switching when special workspace present

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#157]
**Describe the bug**
Kind of one feature and one bug. 

1) When creating a special workspace (by sending a window to it), the workspace can be swicthed to when using workspace,+1 or -1. It appears at the end, both the lower end (workspace,-1 when on the lowest numeric workspace) or at the upper end (when doing workspace,+1 from the highest numerical ws). Nothing really wrong with the special WS being visible/switchable to (was that a design choice? why?), but it being visible from both end looks weird.
2) when switching to the special WS, and back (again using workspace,+1 or -1), it skips the first WS it encounter. That is, say I have WS 1 and 2. I send a window to the special WS, thus creating it. 
then I go workspace,+1 several time: the WS go 1,2,special. 
If now I go workspace,-1 several time, what it does is: 1,special. It skips 2.
Same if I start from the bottom and go up, it goes (from special): 2, special - it skips 1.

I guess that's a bug. 

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

*Please do NOT attach coredumps from any packaged version of Hyprland (AUR, etc.). Compile manually, and THEN attach a coredump of that.*

**Comment by frigaut** [comment]
right

**Comment by vaxerski** [comment]
did f5cdb5b95e13928316e83c32f0351654734a2bde fix it?

**Comment by frigaut** [comment]
give me a mn

**Comment by frigaut** [comment]
yep, fixed
