### ISSUE TITLE
Checks incase you move a window to the currently focused workspace

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#158]
**Describe the bug**

If I am focused on workspace 1 and I move a window to workspace 1 hyprland assumes it is no longer present but it is still on the screen

**Images/videos/anything that would help**

Before:
![20220603_09h39m06s_grim](https://user-images.githubusercontent.com/68993177/171820062-e32148eb-b0c1-4f21-a6a4-5e7089969988.png)
After:
![20220603_09h39m28s_grim](https://user-images.githubusercontent.com/68993177/171820092-3681eb94-daa0-41ee-b8ca-224e737b7ba3.png)

**Comment by vaxerski** [comment]
fixed in 19b17b590c8a2dc19e79542796c7b1b8e65301de
