### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#159]
We've been on 0.2.2 for a fairly long time I would like to be able to use:
- bugfix for moving window to active workspace
- option to lock numlock
- fixing drag on fullscreen window
- fix for https://github.com/vaxerski/Hyprland/issues/157
- fix for https://github.com/vaxerski/Hyprland/issues/147
- fixing the typo in https://github.com/vaxerski/Hyprland/commit/0f28d2ae5515c5f8f6f50cad743f049ce1fda584

**Comment by vaxerski** [comment]
"fairly long time" 

sir its been one day

**Comment by vaxerski** [comment]
done
