### ISSUE TITLE
compiling error in Arch linux

### ISSUE THREAD

**Issue by EvilBoi123** [vaxerski/Hyprland#16]
Don't know what is happening, i've installed every packages as instructed but I got this error 

make all
make[1]: Entering directory '/home/cancel/Hyprland'
make config
make[2]: Entering directory '/home/cancel/Hyprland'
make[2]: Nothing to be done for 'config'.
make[2]: Leaving directory '/home/cancel/Hyprland'
make release
make[2]: Entering directory '/home/cancel/Hyprland'
mkdir -p build && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja
Not searching for unused variables given on the command line.
-- Configuring Hyprland!
-- Configuring Hyprland in Release with CMake!
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cancel/Hyprland/build
cmake --build ./build --config Release --target all -j 10
ninja: no work to do.
make[2]: Leaving directory '/home/cancel/Hyprland'
cd ./hyprctl && make all && cd ..
make[2]: Entering directory '/home/cancel/Hyprland/hyprctl'
g++ -std=c++20 ./main.cpp -o ./hyprctl
make[2]: Leaving directory '/home/cancel/Hyprland/hyprctl'
make[1]: Leaving directory '/home/cancel/Hyprland'
cp ./example/hyprland.desktop /usr/share/wayland-sessions/
cp: cannot create regular file '/usr/share/wayland-sessions/': Not a directory
make: *** [Makefile:72: install] Error 1****

**Comment by vaxerski** [comment]
`sudo mkdir -p /usr/share/wayland-sessions`

**Comment by EvilBoi123** [comment]
> `sudo mkdir -p /usr/share/wayland-sessions`

I'm an idiot., thanks it worked!
