### ISSUE TITLE
Mouse constraints/locking isn't implemented.

### ISSUE THREAD

**Issue by vaxerski** [vaxerski/Hyprland#17]
Especially games, which use the cursor for looking around, e.g. shooters, minecraft, etc. Cannot lock the mouse and thus are unplayable.

**Comment by vaxerski** [comment]
le fixed with 7b1eaca84014d88a420bcbd3f97467f74e82ab33

**Comment by FlyingStitchman** [comment]
Just tested, this does not seem to work with multiple monitors. On the directions that another monitor exists, the mouse can leave the game window and enter the other monitor. I did not see an option in the wiki, so I assumed that locking would be implemented on any `fullscreen` window. The other directions (ones without adjacent monitors) work fine. I tried both Risk of Rain 2 and No Mans Sky.

**Comment by vaxerski** [comment]
I only tried minecraft :P

a game has to request a mouse constraint, but I'll look into it. thanks.

**Comment by FlyingStitchman** [comment]
Just loaded up minecraft, the multi-monitor issues i mentioned are present.

**Comment by vaxerski** [comment]
on non-fullscreen too???

**Comment by FlyingStitchman** [comment]
Window locking only seems to work when the border of the window is the exact same as the border of the entire desktop resolution. If a window is not fullscreen, it does not seem to work (only tested minecraft). If a window is fullscreen, but there is an adjacent screen, the mouse cursor can enter the adjacent screen, although the other sides without an adjacent screen work fine.

**Comment by vaxerski** [comment]
it worked for me perfectly, weirdd

**Comment by FlyingStitchman** [comment]
I just tried recompiling it and it now works (mind you I cloned and compiled it already, but apparently it was not happy for some reason).

**Comment by FlyingStitchman** [comment]
Apologies for reopening this for an unwarranted reason.

**Comment by vaxerski** [comment]
chill, no worries

**Comment by Mikilio** [comment]
I also apologize for reopening this issue. Unfortunately the issue arises also with league of legends installed through lutris. I'm using NixOS.

**Comment by vaxerski** [comment]
Expected behavior, we don't want users playing league of legends.

**Comment by Mikilio** [comment]
> Expected behavior, we don't want users playing league of legends.

I apologize if you have to download the game for debugging.

**Comment by vaxerski** [comment]
There is no debugging needed. It's, again, intended behavior.

**Comment by Mikilio** [comment]
Unless you think there is nothing wrong with the code I will have to reopen the issue. I really didn't want to act like a Karen but I saw no other way. (quitting league has been considered)

**Comment by fortbis** [comment]
Hello, there is a problem in the native game War thunder. Having several monitors, when moving, the cursor goes outside the game on another monitor. No rules with windows do not help. Can you please advise me how I can help with a fix?

**Comment by fortbis** [comment]
Also I can't use gamescope, with nvidia I get 0 fps......

**Comment by XorvatoAmigos** [comment]
@fortbis At this point, I don't know how to solve this problem.
 https://community.gaijin.net/issues/p/warthunder/i/uIasWrliZP8o?comment=gBM9sWds2BnwtrHtHspnqGi7

**Comment by fortbis** [comment]
Is it possible to use a window manager to implement window locking? Like a window rule for example? I'm interested in any solution, thanks!

**Comment by XorvatoAmigos** [comment]
@fortbis https://github.com/hyprwm/Hyprland/issues/1732#issuecomment-1595819110

**Comment by fortbis** [comment]
@vaxerski Is it possible to implement a rule (monitor position script) only for a specific workspace? 
I apologize if I didn't notice something before I asked the question.

**Comment by vaxerski** [comment]
you can probably script that with socket2.

Also, please don't necropost, this issue has been solved for over 1.5 year.
