### ISSUE TITLE
Segfault on launch

### ISSUE THREAD

**Issue by owenthewizard** [vaxerski/Hyprland#170]
`hyprland.log`: https://dpaste.com/3LVJMZPR2
coredump: attached
[Hyprland.coredump.gz](https://github.com/vaxerski/Hyprland/files/8854307/Hyprland.coredump.gz)

**Comment by vaxerski** [comment]
what version, for the raw coredump I need info on what Hyprland version you are running

**Comment by owenthewizard** [comment]
Additional log: https://dpaste.com/73W4G5X4C
`r679.2bddfa8-1`, `hyprland-git` from AUR.

**Comment by vaxerski** [comment]
well ignoring the fact that your keymap is invalid, 

![image](https://user-images.githubusercontent.com/43317083/172452359-7be98aeb-08aa-49db-a836-10f1e38c60d9.png)

this is your coredump. I've said it multiple times, do not use the AUR version when giving me a coredump.

**Comment by owenthewizard** [comment]
Fixing the keymap resolved the issue.
