### ISSUE TITLE
Focus doesn't follow mouse when moving a window to another workspace

### ISSUE THREAD

**Issue by frigaut** [vaxerski/Hyprland#172]
See movie. When I move the upper right terminal window to another workspace, even though the mouse is on it in this new workspace, the focus has been moved to another window.

My guess is that you are computing on which window the focus should be *before* the addition of the new window.

https://user-images.githubusercontent.com/613346/172632879-f3306330-64e5-4aba-820f-502b79663716.mp4

**Comment by vaxerski** [comment]
fixed in 8f0b963729fbce703222defdb1598bdb6f08849e

**Comment by frigaut** [comment]
yeess. 
Cheers.
