### ISSUE TITLE
How to handle lid switching ?

### ISSUE THREAD

**Issue by Ogromny** [vaxerski/Hyprland#175]
Hi,

I'm trying to auto turn off my laptop's screen when i close the lid, I have tried with `elogind`, but it doesn't seem to works. With wayland we can use `bindswitch` command but it seems there is nothing like that in Hyprland. 

Is there a keyword or anything like that undocumented ?

**Comment by vaxerski** [comment]
no clue, i dont use a laptop. maybe ask frigonaut, he uses a laptop often, he's on the discord server, under the alias of Sasaigo.

**Comment by fufexan** [comment]
Usually `logind` handles hardware switches like lid events. I'm not sure if elogind needs special configuration for it, but logind should work OOTB. What distro are you running?

**Comment by Ogromny** [comment]
Void linux
