### ISSUE TITLE
Scaling on HiDPI

### ISSUE THREAD

**Issue by patrickaldis** [vaxerski/Hyprland#183]
Currently running on a 4k display 2x scaling with: `monitor=,3840x2160@60,0x0,2`

However, at the moment what I'm seeing is 1080p upscaled to 4k, so all the objects on the screen (except from the cursor) are pixelated. Is this the normal behaviour? I saw this issue - https://github.com/vaxerski/Hyprland/issues/79 but see it's now closed.

Thanks!

**Comment by vaxerski** [comment]
no, scaling works fine for me on my testing setup. Dunno what your issue is. Maybe the apps you're using don't support scaling?

**Comment by patrickaldis** [comment]
Yes!!! This seems like a total waste of time now, but thanks. I was using alacritty, I guess that doesn't play well. Switched to kitty

**Comment by patrickaldis** [comment]
I think any xwayland app is pixelated - discord, alacritty,

**Comment by fufexan** [comment]
Alacritty is wayland-native. Why would it run under xwayland?

**Comment by patrickaldis** [comment]
I didn't know this, just trying out a wayland wm for the first time. currently alacritty, discord, vscode, spotify and various others all run pixelated. I was assuming this was just because they were x windows

**Comment by fufexan** [comment]
I'm not sure why alacritty behaves like that, but it shouldn't. The rest are X apps so it's expected.
