### ISSUE TITLE
Workspace or any sway/module is not showing in Waybar

### ISSUE THREAD

**Issue by EuCaue** [vaxerski/Hyprland#185]
- Steps to reproduce:
- Install the hyrpland-git from aur
- Install the waybar compile with #define HAVE_WLR #define USE_EXPERIMENTAL in the file include/factory.hpp

- Expected outcome
- Workspaces show in the waybar...

- Noted outcome
- no workspaces in waybar... or any sway/*

[waybar output in terminal](https://pastebin.pl/view/raw/d5071c00)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8882997/hyprland.log)
using SDDM..

_Sorry for my English_

**Comment by vaxerski** [comment]
is this sway? no sway/ modules will work.

wlr/workspaces is the module that works for workspaces. Please consult the waybar documentation.

**Comment by EuCaue** [comment]
Sorry.... I read the documentation... but for any reason a skipped this part.. 
The problem is solved... :)
