### ISSUE TITLE
Hyprland crashes on keypress after start from tty

### ISSUE THREAD

**Issue by dgpalmieri** [vaxerski/Hyprland#186]
I installed hyprland-git from the AUR earlier this evening, and when starting it from a tty it seems to initialize fine, but as soon as I press any key it segfaults. Any advice is appreciated!

[coredump.txt](https://github.com/vaxerski/Hyprland/files/8883171/coredump.txt)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8883172/hyprland.log)

**Comment by vaxerski** [comment]
![Screenshot_20220611-061553_Chrome.jpg](https://user-images.githubusercontent.com/43317083/173172146-631faa1d-9235-4f9f-a53c-202ec27acd85.jpg)

reading the log yourself is not a terrible idea you know

**Comment by nonetrix** [comment]
It should perhaps make a default config if none is detected

**Comment by vaxerski** [comment]
it does that. It just sometimes can't for some reason on some people's pcs

**Comment by R-VL** [comment]
> I installed hyprland-git from the AUR earlier this evening, and when starting it from a tty it seems to initialize fine, but as soon as I press any key it segfaults. Any advice is appreciated!
> 

Make sure there's a directory called "hypr" inside your ~/.config

Hope that helps ~

**Comment by vaxerski** [comment]
ah yeah that might explain why hyprland fails to autogenerate a config

**Comment by vaxerski** [comment]
closing, incativity and solved

**Comment by dgpalmieri** [comment]
Many thanks to @R-VL for the advice that helped me solve this!

I'm planning on making a PR sometime in the near future that will eliminate this problem (or at least provide more verbose logging) for other users.

**Comment by fufexan** [comment]
@dgpalmieri it was already solved in https://github.com/vaxerski/Hyprland/pull/223
