### ISSUE TITLE
SuperShift+BackTab binding not working

### ISSUE THREAD

**Issue by CaptainAsbestos** [vaxerski/Hyprland#188]
### Steps to reproduce

In my i3 and sway config, I like to use meta+Tab and meta+BackSpace to walk through workspaces, adding shift to reverse their behaviour. Here's the lines in my hyprland.conf:

```
bind=SUPER,tab,workspace,m+1
bind=SUPER,backspace,workspace,m-1
bind=SUPERSHIFT,backspace,workspace,m+1
bind=SUPERSHIFT,tab,workspace,m-1
bind=SUPERSHIFT,backtab,workspace,m-1
```
### Expected Outcome

Super+Shift+Tab ought to do what it's configured to.

### Noted Outcome

I seems the last two lines don't work, and they don't produce an error message. I tried backtab on the suggestion of the FAQ.

### Extra info

Running Hyprland v0.4.0beta on OpenSuSE Leap 5.18-1-1 default on a ThinkPad L14 Gen 1.

**Comment by vaxerski** [comment]
probably shift changed the tab to something else, read the wiki please. You can use xev or wev to find the shifted key.

Furthermore, what the hell is a backtab?

**Comment by CaptainAsbestos** [comment]
Thanks for getting back to me! Line 512 of [this list](https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h) from the FAQ on the wiki has "backtab" as an option; I figured that would be what tab turns into. No idea what a backtab is though haha.

Thanks for the wev suggestion, turns out that the key becomes "ISO_LEFT_TAB" on my PC; edited the config to reflect that and it's now working as expected.
