### ISSUE TITLE
Tabbed containers

### ISSUE THREAD

**Issue by Ashe** [vaxerski/Hyprland#19]
**Describe in detail your idea.**
My primary usecase of i3/sway is being able to ~~stack~~ tab windows in a container. I have a super ultra wide monitor and I have 3 columns of windows with my 'main' window in the middle. I always make this a ~~stacked~~ tabbed container so I can easily switch from my web browser / terminal / steam / game all being in the middle of my monitor. It's also nice just to declutter spare windows.

It has similar usecases as workspaces, but since my monitor is so wide I don't need an entire new screen of windows, I just want to easily repurpose my main area.

This is important to me and I'm unlikely to switch to this as my main wm unless this is a feature. Other than that though, it really is quite a nice experience! About time we had a fresh wm!

**Comment by vaxerski** [comment]
can you post a demo of the feature? Link to a youtube video where someone uses it is enough.

**Comment by Ashe** [comment]
I think in i3 it's actually named a 'tabbed' layout. I guess this is better since calling it stacked implies we're going from tiling window management to stacking window management.

https://youtu.be/RUKXZjxou3U?t=85

I linked a YouTube clip (not mine) where the person has a full-screen container and then converts it to a tabbed layout, so that rather than windows tiling horizontally or vertically within it, they are instead hidden while exposing 'tabs' at the top (like a web browser). I don't use this feature in full-screen like in the video (that's when workspaces are typically used anyway), I use this for a portion of my scree; I'd only switch my central container to a tabbed layout.

I hope this helps!

**Comment by vaxerski** [comment]
okay, can implement in dwindle.

**Comment by vaxerski** [comment]
added in this b6a93b2f0383fc8f084c7757f0f67b8c0ebeccc7 bad boy, should work, mostly tested.

see the new dispatchers and configs for border color in the wiki.

Cheers.

**Comment by Ashe** [comment]
> added in this [b6a93b2](https://github.com/vaxerski/Hyprland/commit/b6a93b2f0383fc8f084c7757f0f67b8c0ebeccc7) bad boy, should work, mostly tested.
> 
> see the new dispatchers and configs for border color in the wiki.
> 
> Cheers.

I'm sorry I bet actually thanked you for doing this! I've been very busy but it's still on my to-do list to use your window manager and now that you've got tabbed containers I'm going to evangelize you!

Thanks so much!
