### ISSUE TITLE
Natural scrolling for touchpad only

### ISSUE THREAD

**Issue by PowerBall253** [vaxerski/Hyprland#193]
With <https://github.com/vaxerski/Hyprland/issues/63>, natural scrolling was implemented. However, the setting makes it so that both mouse and touchpad have reverse scrolling, which is undesirable by most people. Would it be possible to implement natural scrolling that only affects the touchpad? Thank you.

**Comment by vaxerski** [comment]
input config per device is planned, but not implemented yet.

**Comment by PowerBall253** [comment]
I have opened a PR with a quick implementation of this: <https://github.com/vaxerski/Hyprland/pull/195>

**Comment by vaxerski** [comment]
closing then
