### ISSUE TITLE
Screen flicker on first start

### ISSUE THREAD

**Issue by EPNero** [vaxerski/Hyprland#201]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

I've recently switched to Hyprland (tried both `yay -S hyprland-git` and compiling myself) but I can't seem to be able to launch Hyprland correctly. Upon start, screen flickers until a key (any key) that corresponds to something in my `hyprland.conf` (e.g. SUPER+Return for terminal). 
[Here](https://termbin.com/zgsb) is my `Hyprland.log` (uploaded to termbin for convenience) 

This is a laptop with a discrete *NVIDIA* card, ***however***, it should be using the integrated Intel GPU by default as I have configured EnvyControl for that purpose. And even with EnvyControl removed, the issue continues to occur.

Any help would be appreciated!

P.S.

**Comment by vaxerski** [comment]
is that an issue? if doing anything fixes it, it shouldn't really be.

I've noticed it on my poopy laptop too, it's probably an issue with either of those two:

some laptops have 2 active outputs, for some reason, you should prolly disable one cuz it doesnt technically exist

it might be an issue with double-buffered damage state, doing a rollback on the second buffer being empty

**Comment by EPNero** [comment]
> is that an issue? if doing anything fixes it, it shouldn't really be.
I would argue it should not be happening in the first place. While do I admit it's not *significant* as it can be fixed by simply doing something you basically *have to do* on a window manager; it could result in something significant. But what do I know?

> some laptops have 2 active outputs, for some reason, you should prolly disable one cuz it doesnt technically exist
I don't know what you mean by 2 active outputs. Are you referring to xrandr outputs, as if there are two monitors? If not, how can I check and disable the second output?

**Comment by vaxerski** [comment]
check the debug:overlay

**Comment by EPNero** [comment]
issue is resolved by replacing `eDP-1` with `DP-1` in `hyprland.conf`

thank you for your time
