### ISSUE TITLE
[QUESTION] Is it working with i3?

### ISSUE THREAD

**Issue by JukoiDev** [vaxerski/Hyprland#203]
Hello, I am very new to ricing community. I chose i3 as my window manager and Hyprland as my compositor. Will it work together fine?

**Comment by frigaut** [comment]
No, you can not run hyprland within i3. Not compatible.

**Comment by vaxerski** [comment]
hyprland is not an xorg compositor

**Comment by JukoiDev** [comment]
kk, thank you!
