### ISSUE TITLE
Enable numlock on startup

### ISSUE THREAD

**Issue by K4zoku** [vaxerski/Hyprland#204]
Please add a hyprctl command or a config option to enable numlock on startup.

**Comment by vaxerski** [comment]
tried, didnt work. Idk how to do it properly. If anyone wants to fix it, feel free. Wayfire and Sway can do it iirc

**Comment by feilongfl** [comment]
For the convenience of those who search here subsequently, add memo here.

check [this link](https://wiki.hyprland.org/Configuring/Basic-Config/#:~:text=false-,numlock_by_default,-lock%20numlock%20by) to enable numlock:

**Comment by ideasman42** [comment]
> For the convenience of those who search here subsequently, add memo here.
> 
> check [this link](https://wiki.hyprland.org/Configuring/Basic-Config/#:~:text=false-,numlock_by_default,-lock%20numlock%20by) to enable numlock:

The link is broken, this works:

```
input {
   # ... snip ...
    numlock_by_default = true
}

```

**Comment by feilongfl** [comment]
> > For the convenience of those who search here subsequently, add memo here.
> > check [this link](https://wiki.hyprland.org/Configuring/Basic-Config/#:~:text=false-,numlock_by_default,-lock%20numlock%20by) to enable numlock:
> 
> The link is broken, this works:
> 
> ```
> input {
>   # ... snip ...
>   numlock_by_default = true
> }
> ```

new document is [here](https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Variables/#:~:text=%5B%5BEmpty%5D%5D-,numlock_by_default,-Engage%20numlock%20by)

**Comment by Kampuz** [comment]
The documentation is actually in [here](https://wiki.hypr.land/Configuring/Variables/#input)

**Comment by M4nt0** [comment]
It's now [here](https://wiki.hypr.land/Configuring/Basics/Variables/#input)
