### ISSUE TITLE
Include `assets` and `LICENSE` in binary releases

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#207]
The `assets` folder and `.git` should be included in the binary releases. Not doing so breaks the `hyprland` and `hyprland-bin` AUR packages.

**Comment by vaxerski** [comment]
assets i can see why, but .git?

**Comment by vaxerski** [comment]
that is because the freedesktop gitlab is dead

**Comment by vaxerski** [comment]
can you repack the latest release with the files and send me the tar on discord? i'd update it

**Comment by ThatOneCalculator** [comment]
Done, check discord

**Comment by vaxerski** [comment]
done
