### ISSUE TITLE
Write a changelog on release

### ISSUE THREAD

**Issue by tpkee** [vaxerski/Hyprland#208]
Reading commits' messages to know what changed isn't the most immediate thing, and since the project is getting quite big wouldn't it be better to have a full changelog on every release?

**Comment by vaxerski** [comment]
i'm lazy.

**Comment by tpkee** [comment]
feel ya on that one, let's hope someone will propose to do it then lol.
Or you prefix your changes with Feature:,Fix: etc and then [merge](https://git-scm.com/docs/git-log#_commit_limiting) all the messages from date x to release date

**Comment by ErikReider** [comment]
GitHub allows you to auto generate the changelog

**Comment by vaxerski** [comment]
ok then, if it does i will.
