### ISSUE TITLE
Hyprand doesn't start after reinstall

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#21]
It had been like a week and a half since I last updated it so I redid the installation exactly as the instructions say but when I tried to log in to it it just went straight back to the display manager

log:
{
[LOG] Hyprland init finished.
[LOG] Creating the CHyprError!
[LOG] Creating the KeybindManager!
[LOG] Creating the ConfigManager!
[LOG] Creating the ThreadManager!
[LOG] Creating the InputManager!
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 3.2 Mesa 22.0.1
[LOG] Vendor: nouveau
[LOG] Renderer: NV106
[LOG] Supported extensions size: 137
[LOG] Reloading the config!
[LOG] Hypr socket started on port 9187
[LOG] Shaders initialized successfully.
[LOG] Creating the HyprRenderer!
[LOG] Creating the XWaylandManager!
[LOG] Registered signal for owner ba3ac6b0: ba3ac6e8 -> b8547220 (owner: XWayland Manager)
[LOG] Registered signal for owner ba3ac6b0: ba3ac6f8 -> b8547200 (owner: XWayland Manager)
[LOG] CHyprXWaylandManager started on display :0
[LOG] Creating the LayoutManager!
[LOG] Creating the AnimationManager!
[LOG] Registered signal for owner b9ae10c0: b9ae10e8 -> b8546db0 (owner: Backend)
[LOG] Registered signal for owner ba2a5f10: ba2a5f58 -> b8546d70 (owner: XDG Shell)
[LOG] Registered signal for owner ba2a5fe0: ba2a5ff8 -> b8546d50 (owner: WLRCursor)
[LOG] Registered signal for owner ba2a5fe0: ba2a6008 -> b8546d30 (owner: WLRCursor)
[LOG] Registered signal for owner ba2a5fe0: ba2a6018 -> b8546d10 (owner: WLRCursor)
[LOG] Registered signal for owner ba2a5fe0: ba2a6028 -> b8546cf0 (owner: WLRCursor)
[LOG] Registered signal for owner ba2a5fe0: ba2a6038 -> b8546cd0 (owner: WLRCursor)
[LOG] Registered signal for owner b9ae10c0: b9ae10d8 -> b8546cb0 (owner: Backend)
[LOG] Registered signal for owner b9ae0fb8: ba324418 -> b8546c90 (owner: Seat)
[LOG] Registered signal for owner b9ae0fb8: ba324428 -> b8546c70 (owner: Seat)
[LOG] Registered signal for owner b9ae0fb8: ba324468 -> b8546c10 (owner: Seat)
[LOG] Registered signal for owner b9ae0fb8: ba324478 -> b8546bf0 (owner: Seat)
[LOG] Registered signal for owner ba324580: ba3245a0 -> b8546d90 (owner: LayerShell)
[LOG] Registered signal for owner ba2a19d0: ba2a19f0 -> b8546dd0 (owner: OutputLayout)
[LOG] Registered signal for owner ba324890: ba3248c8 -> b8546c50 (owner: OutputMgr)
[LOG] Registered signal for owner ba324890: ba3248d8 -> b8546c30 (owner: OutputMgr)
[LOG] Registered signal for owner ba324970: ba3249a0 -> b8546bd0 (owner: InhibitMgr)
[LOG] Registered signal for owner ba324970: ba3249b0 -> b8546bb0 (owner: InhibitMgr)
[LOG] Running on WAYLAND_DISPLAY: wayland-0
[LOG] Attached a keyboard with name Power Button
[LOG] Registered signal for owner ba3ad6b0: ba410158 -> ba3ad6b8 (owner: Keyboard)
[LOG] Registered signal for owner ba3ad6b0: ba410148 -> ba3ad720 (owner: Keyboard)
[LOG] Registered signal for owner ba3ad6b0: ba410028 -> ba3ad788 (owner: Keyboard)
[LOG] New keyboard created, pointers Hypr: ba3ad6b0 and WLR: ba410008
[LOG] Set the keyboard layout to  and variant to 
[LOG] Attached a keyboard with name Power Button
[LOG] Registered signal for owner ba3cd170: ba416f58 -> ba3cd178 (owner: Keyboard)
[LOG] Registered signal for owner ba3cd170: ba416f48 -> ba3cd1e0 (owner: Keyboard)
[LOG] Registered signal for owner ba3cd170: ba416e28 -> ba3cd248 (owner: Keyboard)
[LOG] New keyboard created, pointers Hypr: ba3cd170 and WLR: ba416e08
[LOG] Set the keyboard layout to  and variant to 
[LOG] Attached a keyboard with name Smart Smart Wireless Device
[LOG] Registered signal for owner ba2ae570: ba48f518 -> ba2ae578 (owner: Keyboard)
[LOG] Registered signal for owner ba2ae570: ba48f508 -> ba2ae5e0 (owner: Keyboard)
[LOG] Registered signal for owner ba2ae570: ba48f3e8 -> ba2ae648 (owner: Keyboard)
[LOG] New keyboard created, pointers Hypr: ba2ae570 and WLR: ba48f3c8
[LOG] Set the keyboard layout to  and variant to 
[LOG] Attached a keyboard with name Smart Smart Wireless Device
[LOG] Registered signal for owner ba48abc0: ba504188 -> ba48abc8 (owner: Keyboard)
[LOG] Registered signal for owner ba48abc0: ba504178 -> ba48ac30 (owner: Keyboard)
[LOG] Registered signal for owner ba48abc0: ba504058 -> ba48ac98 (owner: Keyboard)
[LOG] New keyboard created, pointers Hypr: ba48abc0 and WLR: ba504038
[LOG] Set the keyboard layout to  and variant to 
[LOG] Attached a mouse with name Smart Smart Wireless Device
[LOG] New mouse created, pointer WLR: ba5041c0
[LOG] Attached a keyboard with name Logitech G305
[LOG] Registered signal for owner ba3a5a70: ba48a7a8 -> ba3a5a78 (owner: Keyboard)
[LOG] Registered signal for owner ba3a5a70: ba48a798 -> ba3a5ae0 (owner: Keyboard)
[LOG] Registered signal for owner ba3a5a70: ba48a678 -> ba3a5b48 (owner: Keyboard)
[LOG] New keyboard created, pointers Hypr: ba3a5a70 and WLR: ba48a658
[LOG] Set the keyboard layout to  and variant to 
[LOG] Attached a mouse with name Logitech G305
[LOG] New mouse created, pointer WLR: ba48a7e0
[WARN] getMonitorFromCursor: cursor outside monitors??
}

Also how would I uninstall or update it without tracking down and deleting all its files then reinstalling or just reinstalling to overwrite previous files?

**Comment by vaxerski** [comment]
I just merged a PR to add `make uninstall`

I've seen this bug before, what I found works (for now, I'll fix that in the future) is to not move the mouse until your monitors are turned on and displaying an image.
