### ISSUE TITLE
Make GitHub mirror of wlroots on Freedesktop

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#211]
Given the instability/downtime of the freedesktop gitlab server, a mirror should be made on GitHub and used as the submodule.

**Comment by vaxerski** [comment]
make it then

**Comment by vaxerski** [comment]
open an issue there :troll:

**Comment by ThatOneCalculator** [comment]
WAIT I think I got it one sec

**Comment by vaxerski** [comment]
will it autoupdate tho

**Comment by ThatOneCalculator** [comment]
It should? Idk too much about mirrors

**Comment by vaxerski** [comment]
ok then if you want you can make a pr pointing to the repo

**Comment by Froggo8311** [comment]
lollll
