### ISSUE TITLE
Cannot compile also how do I open a script in the terminal?

### ISSUE THREAD

**Issue by TheLastTeapot** [vaxerski/Hyprland#217]
I successfully cloned and compiled official wlroots, and cloned Hyprland. Hyprland failed with message 
"
FAILED: CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o
/usr/bin/c++ -DGIT_BRANCH=\"\" -DGIT_COMMIT_HASH=\"\" -DGIT_COMMIT_MESSAGE=\"\" -DGIT_DIRTY=\"dirty\" -I/home/noah/Hyprland/. -isystem /usr/include/cairo -isystem /usr/include/lzo -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/pixman-1 -isystem /usr/include/pango-1.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libdrm -O3 -DNDEBUG -std=c++20 -DWLR_USE_UNSTABLE -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -pthread -MD -MT CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o -MF CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o.d -o CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o -c /home/noah/Hyprland/src/render/OpenGL.cpp
/home/noah/Hyprland/src/render/OpenGL.cpp: In member function ‘void CHyprOpenGLImpl::begin(SMonitor*, pixman_region32_t*, bool)’:
/home/noah/Hyprland/src/render/OpenGL.cpp:135:5: error: ‘wlr_matrix_projection’ was not declared in this scope; did you mean ‘wlr_matrix_project_box’?
  135 |     wlr_matrix_projection(m_RenderData.projection, pMonitor->vecPixelSize.x, pMonitor->vecPixelSize.y, WL_OUTPUT_TRANSFORM_NORMAL);  // TODO: this is deprecated
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     wlr_matrix_project_box
"
Also, how do I open a terminal script with a keybind?

If you need, I will give the full output.

**Comment by vaxerski** [comment]
see the wiki for installation instructions

**Comment by TheLastTeapot** [comment]
It worked. If I may ask, why did it make a difference? I had already tried cloning both your mirror of wlroots and the official version, inside and outside the hyprland folder. Why did doing it automatically change anything?

**Comment by TheLastTeapot** [comment]
I see. Is it possible to open a terminal script in an emulator through a keybind?

**Comment by PowerBall253** [comment]
Yep, first check your terminal for an option that allows launching it with a command (usually `-e`), and then you can bind to that command, for example:

```
bind=SUPER,A,exec,alacritty -e /path/to/script.sh
```

**Comment by TheLastTeapot** [comment]
Ah, thank you!
