### ISSUE TITLE
locked bindings

### ISSUE THREAD

**Issue by primalmotion** [vaxerski/Hyprland#219]
I would like to be allow some bindings to work when the screen is locked (with swaylock for instance). For instance I would like to be able to volume up/down play/pause, even if the screen is locked.

Here's how this is done in sway

```
bindsym --locked XF86AudioRaiseVolume exec volume.sh up
bindsym --locked XF86AudioLowerVolume exec volume.sh down
```

**Comment by vaxerski** [comment]
added in 5541098f2026daed21d87fdaa5c85d8329c8cfbc

use `bindl=`, rest the same as `bind`

**Comment by primalmotion** [comment]
awesome! gonna try that soon
