### ISSUE TITLE
[HOWTO] Screen sharing in Hyprland with Firefox & Brave

### ISSUE THREAD

**Issue by Overbuffer** [vaxerski/Hyprland#224]
Great project btw!!

So I had to invest a lot of time to make this work so I think it would be helpful to add this info to the documentation. 

The steps I had to take on Fedora 36 to make screen sharing to work were:. 

1. Install portal package for wlroots in fedora:
`sudo dnf install xdg-desktop-portal-wlr`
3. Add 'hyprland' to 'UseIn' at /usr/share/xdg-desktop-portal/portals/wlr.portal:
4. Add to hyperland configfile:
`exec-once=systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK`
`exec-once=hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_ DISPLAY SWAYSOCK`

Maybe there is some "extra command" to add (or remove) to this

Keep rocking! Thanks!

PD: In chromium does not work :D

**Comment by vaxerski** [comment]
chromium runs in XWayland by default, you have to launch it with ozone wayland platform, but that has issues with rendering (blame chromium)

**Comment by vaxerski** [comment]
furthermore, that info is already in the FAQ.

**Comment by Overbuffer** [comment]
ouch! i really did not found it. Sorry

**Comment by vaxerski** [comment]
added the execs to the wiki doe as i forgot them.

**Comment by PowerBall253** [comment]
Shouldn't only one of those execs be needed? (either the systemctl or the dbus one)

**Comment by fufexan** [comment]
You're right. The dbus one is recommended.

**Comment by GustavoPeredo** [comment]
Is there some special step on nixos to achieve this? I'm currently having my browsers (chromium and firefox) crash when trying to screen share. Obs works fine.

**Comment by truvatech** [comment]
Also getting this issue on NixOS. After days of setting up hyprland, I've spent all day today banging my head against this issue of screensharing...
I get the tab/window/screen dialog that pops up, then a secondary pop up asking to either share Screen, window, or region. I can select either of those, but the only one that shows a "preview" back on the Brave browser dialog screen is window share, but then no matter what I select, after I share the window or entire screen, nothing shows up and Brave crashes.

Did not realize something like screen sharing would be such a pain on wayland (well, hyprland) + nixOS

Has anyone made any progress with this or got it working?
Thanks
