### ISSUE TITLE
Socket2 reports multiple activewindow changes, sometimes out of order.

### ISSUE THREAD

**Issue by taylor85345** [vaxerski/Hyprland#225]
Socket2 sends two activewindow reports for every workspace change, presumably the parent window of the workspace and the focused window. For some reason they don't always report in the right order and the parent window reports second despite not being the active window.

This is problematic for scripts that subscribe to socket2 to determine the active window.

**Comment by vaxerski** [comment]
yes it does, correct

**Comment by vaxerski** [comment]
fixed in 4a3f9ccba2cebaf62d6001c2b700367785a7179c

**Comment by taylor85345** [comment]
Confirmed, thx
