### ISSUE TITLE
Failed to allocate device list.

### ISSUE THREAD

**Issue by mathiasbolle** [vaxerski/Hyprland#228]
I got the following error message Afte installing Hyprland with the hyprland-bin package from the AUR. It happens after i click a random key on my keyboard (after launching Hyprland)
![IMG_20220616_153329.jpg](https://user-images.githubusercontent.com/79169737/174081607-b249ac27-4644-4aec-9de1-3b7c9b1c60e2.jpg)

**Comment by vaxerski** [comment]
you dont have a config, read the wiki ples

**Comment by mathiasbolle** [comment]
I have, i wget the hyprland.conf from the example dir from the github repo.

![IMG_20220616_153757.jpg](https://user-images.githubusercontent.com/79169737/174082393-2229fb8c-26da-44e1-a22c-1f27d1d39ef0.jpg)

**Comment by vaxerski** [comment]
![Screenshot_20220616-145654_Firefox Beta.jpg](https://user-images.githubusercontent.com/43317083/174086262-78c5ace3-86d6-44ac-ad13-b44f5903d715.jpg)

please read the wiki, again.
