### ISSUE TITLE
Assign specific workspaces to specific monitors

### ISSUE THREAD

**Issue by bazuin-32** [vaxerski/Hyprland#229]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

I have read the wiki many times over, and I can't figure out how (or if it's possible) to do this. I have 2 monitors, `HDMI-A-2` and `HDMI-A-1`. I organize them in my config like so:
```
monitor=HDMI-A-2,1920x1080@60,0x0,1
monitor=HDMI-A-1,1920x1080@60,1920x0,1
```

I want to have specific workspaces on each monitor, e.g. `HDMI-A-2` has workspaces 1-5, and `HDMI-A-1` has 6-10.

In bspwm, I would do the following:
```
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10
```

I'd like to be able to achieve the same thing in Hyprland.

**Comment by Rhymen** [comment]
Check out the advanced config [wiki](https://github.com/vaxerski/Hyprland/wiki/Advanced-config#monitors) 

```
workspace=DP-1,1
```

**Comment by fufexan** [comment]
Workspaces are dynamically created, like in sway. You can assign the starting workspaces, for example.
```
workspace=DP-1,1
