### ISSUE TITLE
NVIDIA rendering issues: monitor flicker, brightness and scaling

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#23]
monitor is about half as bright as it should be and flickers like a flourescent lightbulb, mouse moves really slowly, and gtk apps are displayed smaller than they should be, but the buttons are where they would be if it was full size

https://docs.google.com/document/d/1ZcqtrDItOpp2G71IoPTTfpQW_xwhMiuQoV1E1c58iaY/edit?usp=sharing

**Comment by vaxerski** [comment]
Please next time attach the log, not post it into a google drive.

I can see you're using an NVIDIA GPU and are experiencing rendering issues. I have no way of testing ANYTHING on NVIDIA as I don't have an NVIDIA card.

It's safe to assume the issues are from NVIDIA being NVIDIA, even though you are using nouveau.

**Comment by niwheeler07** [comment]
I couldn't attach the log, it was too big to paste in and when I tried to attach it firefox closed. I guess there's nothing I can do about it then?

**Comment by vaxerski** [comment]
If you aren't a programmer, not really. I will mention in the wiki NVIDIA being unsupported for now.

If anyone with an NVIDIA card wants to contribute, feel free.

One thing you can try is to use the proprietary driver, and try the workarounds that work for Sway, as Sway should work similiarly to Hyprland (although no promises here)

**Comment by niwheeler07** [comment]
I'll be a programmer eventually, but for now I'll try that. Thanks!

**Comment by noahofcarpetballfame** [comment]
This seems to be the same issue as https://github.com/swaywm/wlroots/issues/2874
However, that solution did not work, it just made the screen blank.
