### ISSUE TITLE
Half-sized resolution with HDMI

### ISSUE THREAD

**Issue by paulhersch** [vaxerski/Hyprland#237]
Using my Laptop and my Desktop, proper sizing via HDMI doesn't work. I have confirmed via wlr-randr, that the monitor supports the resolution i want it to use, and even applies it, but hyprland reports a wrong size.

```
-> wlr-randr
...
 1920x1080 px, 60.000000 Hz (preferred, current)
...
-> wlr-randr --output HDMI-A-1 --mode 1920x1080@60Hz
(nothing changes, because resolution is applied)

-> hyprctl monitors
Monitor HDMI-A-1 (ID 0):
	960x540@60.000000 at 0x0
	active workspace: 1 (1)
	reserved: 0 37 0 0
```
Setting the monitor resolution via the following line in the config file also didn't work
```monitor=HDMI-A-1,1920x1080@60,0x0,2```

I am pretty sure this is a bug either with hyprland as this occurs with different monitors on different systems, with the common factor being the HDMI connection.

**Comment by vaxerski** [comment]
well you have your scale set to 2, so the effective resolution is reported correctly.

**Comment by paulhersch** [comment]
OHH
*facepalm*
i thought this would be the workspace the output would usually take
somehow misread the Advanced Configuration page
