### ISSUE TITLE
Don't use sudo in the makefile

### ISSUE THREAD

**Issue by dr460nf1r3** [vaxerski/Hyprland#238]
`cd wlroots && sudo ninja -C build/ install`
Making use of `sudo` to install the package should not be required. In the case of Archlinux's `makepkg`, we don't need these rights to properly finish the packaging process. Furthermore, this breaks automated builds in clean chroots which don't have a superuser set up.

**Comment by vaxerski** [comment]
ninja requires superuser permissions because of copying to /usr

**Comment by dr460nf1r3** [comment]
Yeah, I get that. Wouldn't the usual way be something like `make config` followed by either `make install` or `sudo make install`, as required? 
Currently we have `sudo` hard coded in the makefile, which makes proper packaging hard without applying changes. I am just suggesting this to make the whole process easier for people who want to provide this application to people without having to patch the makefile beforehand.

**Comment by vaxerski** [comment]
maybe, I'll see once I get back from vacation

**Comment by dr460nf1r3** [comment]
Thanks! Enjoy your vacation :)

**Comment by vaxerski** [comment]
I know doas exists, but frankly, just like 99% of other linux users, I do not care.
