### ISSUE TITLE
Screen blinking rapidly when starting Hyprland

### ISSUE THREAD

**Issue by Dickby** [vaxerski/Hyprland#243]
Hi,
Every time i start Hyprland from it blinks very rapidly until i invoke a command that changes something on the screen.
Having some experience with graphics i would guess that it has to do with the double buffering.
If there was only one time that the screen was drawn, and then you swap te buffers, the other one is still black, so i get blinking in a frequency of the screen refresh rate.
So it just has to be dawn two times once Hyprland was started.
Thanks

**Comment by vaxerski** [comment]
yes thats correct

**Comment by vaxerski** [comment]
it will be, I have not said it won't be. I'm just on holiday and cant fix it atm, but I'm aware of the issue

**Comment by vaxerski** [comment]
fixed in ff49f2244069124d366e2eba5e5474398a14281a
