### ISSUE TITLE
Can I get the wallpapers on your READMEs?

### ISSUE THREAD

**Issue by natsukagami** [vaxerski/Hyprland#244]
They look amazing <3

**Comment by vaxerski** [comment]
I don't remember the links (obviously) but afaik the anime ones were from alphacoders 4k anime tag

**Comment by vaxerski** [comment]
![yqblh0h84vf81](https://user-images.githubusercontent.com/43317083/174894877-4aeea321-391f-40c9-b37f-d0d7b5751ac6.jpg)
![1123250](https://user-images.githubusercontent.com/43317083/174894885-7ad293c8-9755-4485-80f6-c85a6b28f656.png)

Insallah github doesnt rape the quality.
