### ISSUE TITLE
Some Applications fail to Autostart

### ISSUE THREAD

**Issue by taylor85345** [vaxerski/Hyprland#25]
**Describe the bug**
Some applications fail to Autostart, or start in an unusable state when launched using `exec=` or `exec_once=`. This includes:

- `swaybg` fails to load on first launch after reboot. Reloading the config or logging out and back in resolves
- `foot --server` loads and runs in background, but is inaccessible to `footclient`. Client reports no server running
- Electron applications (Discord, Element, Caprine) fail to load entirely.

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8475276/hyprland.log)

**Comment by vaxerski** [comment]
dear user,

it is with great pleasure that I may say the above issue has been resolved with the commit 17f63bf3e8abf339279a0c0d6df3b618c172476b.

Kind regards,
vaxry.

**Comment by taylor85345** [comment]
I am happy to report that `exec-once` is being significantly less wack. `exec` still exhibits the problems above, but moving the commands in question to `exec-once` resolves all of the issues for my use case.

**Comment by vaxerski** [comment]
dear user,

it is with great pleasure that I report that `exec` has also been fixed in c68eaafd16c3fde76b2376087f99c922c5a68478

Kind regards,
vaxry.

**Comment by taylor85345** [comment]
Great! Love the work you're doing here by the way!

**Comment by vaxerski** [comment]
thanks :)
