### ISSUE TITLE
Launching makes monitor give an "OUT OF RANGE" error

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#27]
**Describe the bug**

Launching Hyprland from the TTY makes my *monitor* give an OUT OF RANGE error (which means that it's trying to display at a resolution it can't). 

I'm using the exact config from the example, with 2560x1440@144, which *should* be fine.

**Comment by vaxerski** [comment]
So, I am assuming it works as expected on 1080p60? launch it that way then. Then, install weston, and use the `weston-info` util. If your resolution is missing from there, it means something is wrong with your display. You might want to force the resolution with a kernel launch param.

**Comment by ThatOneCalculator** [comment]
> So, I am assuming it works as expected on 1080p60?

Nope. No matter what I set it to, it does the same thing. Even 1920x1080@60.

**Comment by vaxerski** [comment]
please attach a coredump, and the log file in /tmp/hypr/hyprland.log, and, if there are red errors in the TTY, those as well.

**Comment by ThatOneCalculator** [comment]
Closed by latest commits
