### ISSUE TITLE
Mouse cursor becomes invisible after opening a window

### ISSUE THREAD

**Issue by mdk97** [vaxerski/Hyprland#30]
**Describe the bug**
The mouse cursor is visible only after startup, as soon as I open a window (any program) the mouse cursor becomes invisible, but still functional (I can still click on things).

**Images/videos/anything that would help**
I'm using an NVIDIA GPU so weird things are expected to happen I guess.
My specs:
- OS: Artix Linux x86_64
- Kernel: 5.16.12-246-tkg-pds
- CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
- GPU: NVIDIA GeForce GTX 1080
- GPU Driver: NVIDIA 510.60.02
- Resolution: 2560x1080

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8485663/hyprland.log)

**Comment by FlyingStitchman** [comment]
This is a Nvidia Wayland bug. If you add `WLR_NO_HARDWARE_CURSORS=1` to your `/etc/environment`, it should fix the issue. Also for the record, Nvidia (proprietary)works fairly well with Hyprland.

**Comment by vaxerski** [comment]
I'm happy to hear that proprietary nvidia works well, but I am unable to provide any support whatsoever for nvidia users, as I do not own a card from that shithole of a company.

As @FlyingStitchman has mentioned though, you can try WLR_NO_HARDWARE_CURSORS, and also try following a Sway on nvidia tutorial, as both Hyprland and Sway use wlroots, so most tricks that make sway run well on nvidia should also apply to Hyprland.
