### ISSUE TITLE
Blur Tiling Artifacts

### ISSUE THREAD

**Issue by FlyingStitchman** [vaxerski/Hyprland#31]
When using blur on transparent windows, there are lines that run vertically and horizontally where the blur does not affect, forming a sort of grid. When using floating windows, it seems the grid follows the monitor, not the window when it is moving. 
![screenshot](https://user-images.githubusercontent.com/44596866/163325390-cef3f6d9-95e8-4679-bad2-8dd2eac7ed3d.png)
I tested both in foot and konsole and I use swaybg to set the backgrounds. 
Also, this does not affect other wayland compositors such as KDE Plasma and Wayfire.

- OS: Arch Linux
- Kernel: 5.17.1.zen1-1
- GPU: Nvidia 1070
- GPU Driver: 510.54-1
- Dual Monitor: 3440x1440 and 1920x1080

I might test with my igpu later to see if this still happens on intel as I know nvidia is not supported.

Relavent section from `~/.config/hypr/hyprland.conf`
`blur=1`
`blur_size=10`
`blur_passes=3`
Lowering blur passes and blur size does not stop the artifacts from appearing.

[hyprland.log](https://github.com/vaxerski/Hyprland/files/8486731/hyprland.log)

**Comment by vaxerski** [comment]
I know, it's an issue with the shader.

That is precisely why I am planning on switching it to a different one in the future.

**Comment by FlyingStitchman** [comment]
mmhm. Tis what I thought, just thought to make a issue cause it was not yet reported.

**Comment by FlyingStitchman** [comment]
I have found out that when blur is enabled, Blender (so far the only program I have seen it in) has a lot of black line artifacts that flicker  and make it impossible to do stuff in. I assume I should wait for the new blur shader to be implemented before creating a bug report?

**Comment by vaxerski** [comment]
should be fixed with the introduction of dual kawase in e5f8bca41c2c19b798552d5b0e3dbd1bb0b1c2be
