### ISSUE TITLE
NixOS build

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#32]
Good day to you!

Is there someone who was able to create derivation from it?

Thank you!

**Comment by vaxerski** [comment]
no, if you are not on Arch-based systems you have to build this yourself. If you are succesful though, you can give me a tutorial and I'll paste it onto the wiki.

**Comment by fedoranvar** [comment]
as  package will be submitted in nixpkgs i'll close the issue.

all the updates look in   [issue](https://github.com/NixOS/nixpkgs/issues/168392) on nixpkgs

**Comment by vaxerski** [comment]
I will close this as it's unrelated to this repo and the conversation is active over at nix
