### ISSUE TITLE
Latest build 7cd3e5f34affc85ed57345fe3473d64d83151677

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#34]
Good day to you!

I'm trying build latest master, but it showin error

![image](https://user-images.githubusercontent.com/52028706/163596498-e21437c4-841b-4a33-beb9-e1861112e8ab.png)

**Comment by fedoranvar** [comment]
confirm: if i'll apply patch for adding `climits` - error is gone

**Comment by vaxerski** [comment]
added
