### ISSUE TITLE
Allow Disabling Displays

### ISSUE THREAD

**Issue by FlyingStitchman** [vaxerski/Hyprland#35]
There are times where it is necessary to turn off a display. For example, on a VR headset, you do not want it acting as part of the desktop, so it is best to turn it off. It also seems to break certain parts of my main monitor's tiling while I have my HMD plugged in. 

From what I could figure out, displays seem to be initialized in `src/config/ConfigManager.ccp` at around line 140. I assume a condition could be made to check if the monitor's resolution (in the config file) is 0x0, and then make a condition to not initialize it.

**Comment by vaxerski** [comment]
added in 4a966c945bc04982cde1f9ab8f84a67df928c3f1

use
```
monitor=name,disable
```
