### ISSUE TITLE
m_sWLRRenderer was NULL!

### ISSUE THREAD

**Issue by YaoReTian** [vaxerski/Hyprland#40]
**Cannot run Hyprland**

**I am using arch linux in virtualbox**

If I run `Hyprland` on my fresh arch install in Virtualbox, the output is:
`Welcome to Hyprland!`
Then closes and tells me:
`c:698] Could not initialize EGLED (0x3001), message: "eglInitialize"o create screen"`

/tmp/hypr/hyprland.log:
` [CRITICAL] m_sWLRRenderer was NULL!`

**Comment by vaxerski** [comment]
In a virtual box, you prolly don't have a gpu driver, possible fixes:
  install the missing render packages - you use arch, you should know how to
  WLR_RENDERER_ALLOW_SOFTWARE=1 Hyprland

**Comment by paolobettelini** [comment]
@[YaoReTian](https://github.com/YaoReTian) I managed to replicate the issue.

Whilst the virtual machine is off, go to its preferences > `Display` >  check `Enable 3D acceleration`.

Not sure why, but it seems to fix this issue for me.

**Comment by YaoReTian** [comment]
Thank you, that worked perfectly!
The only problem now is that the mouse does not exist, I will see if I can do anything about that, and if not, I will just open another issue.

**Comment by divital-coder** [comment]
Hi guys i was encountering the same exact issue, thanks for the fix, but now i am encountering another issue, my hyprland have nothing working lol

**Comment by kafkainthevoid** [comment]
@divital-coder go to its Preferences > Display > Graphics Controller > VBoxVGA 
things are weird, lol

**Comment by TwelveNight** [comment]
> @paolobettelini Thank you, that worked perfectly! The only problem now is that the mouse does not exist, I will see if I can do anything about that, and if not, I will just open another issue.

Hey,do you solve this problem,I have the same yet
