### ISSUE TITLE
[maybe nvidia] rounded corners arent rounded, they're just kinda chopped when less than size 7

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#42]
Occasionally they just stop being rounded at all depending on where the mouse is. It's exactly the same on Hypr. I'm writing this from my tablet but I will attach a video when I get obs working. It's always been this way, I was waiting to see if it would go away.

**Comment by ThatOneCalculator** [comment]
That's just antialiasing not being implemented yet

**Comment by niwheeler07** [comment]
Ok

**Comment by niwheeler07** [comment]
it's not like that in the screenshots

**Comment by ThatOneCalculator** [comment]
@niwheeler07 Show a screenshot of what ur corners look like

**Comment by vaxerski** [comment]
if you are using the `legacyrenderer` with `blur` it's expected, because it's the legacy renderer

**Comment by niwheeler07** [comment]
https://user-images.githubusercontent.com/82473273/163837468-03a2e382-33aa-469d-9acd-42c9a3b0dee1.mp4

how do i know if i'm using the legacyrenderer

**Comment by vaxerski** [comment]
if you dont know, you have the standard one. they aren't chopped off, it's just that they arent antialiased and you have them very small, meaning they will look like this, yes

**Comment by niwheeler07** [comment]
ok. Will this be fixed eventually? Or is it something I need to do?

**Comment by vaxerski** [comment]
it will be fixed in the future most likely by adding antialiasing, but not like tomorrow future. It's not a critical issue.

**Comment by niwheeler07** [comment]
Ok.
