### ISSUE TITLE
damange_tracking warning (config file parsing error)

### ISSUE THREAD

**Issue by paolobettelini** [vaxerski/Hyprland#43]
Upon starting Hyprland a blue warning appears at the top of the screen

```
Invalid value for general:damage_tracking, supported: full, monitor, none
Hyprland may not work correctly.
```

When looking at the configuration file damage_tracking is set to `none`

```
general {
    max_fps=60
    sensitivity=0.25
    main_mod=SUPER

    gaps_in=5
    gaps_out=20
    border_size=2
    col.active_border=0x66ee1111
    col.inactive_border=0x66333333

    damage_tracking=none # experimental, might have bugs!
}
```

However removing the comment `# experimental, might have bugs!` seems to fix the issue.
I'm assuming that the parsed value for the field includes the whole comment rather than just `none`.

**Comment by vaxerski** [comment]
wrong guess, but fixed in 24316f2e717237d754c6b1ce75be024e4ef34edb
