### ISSUE TITLE
Move/Resize window with shortcuts

### ISSUE THREAD

**Issue by Catvert** [vaxerski/Hyprland#48]
First, congratulations for this beautiful wm, there are still a lot of little bugs and features to implement but it's still a great start!

I was wondering if it was already possible to move and resize windows via keyboard shortcuts? It's a pretty basic feature for a tiling wm, but I couldn't find anything in the documentation that talked about it.

Thanks to you.

**Comment by vaxerski** [comment]
added in 418e2d96aef0b52d1f93eb3dfe7d08906c7c719c and 87b849129427ab664130aa1abc8ade0485328e33
