### ISSUE TITLE
Run Hyprland without xwayland

### ISSUE THREAD

**Issue by struthio** [vaxerski/Hyprland#49]
hi,

I'm trying to build 'wayland only' Linux Install.
Is would be nice to be able to compile Hyprland without XWayland.

**Comment by vaxerski** [comment]
added in bebfe01d731a977c23c325dd37361f6d5f7268c2

see the [wiki page](https://github.com/vaxerski/Hyprland/wiki/Installation#custom-build-flags) for how to build with custom build flags
