### ISSUE TITLE
AUR package issues

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#50]
- `pkg_ver()` doesn't work. 
- Building the latest version causes a crash when from AUR, no crash when from git repo

@sandervankasteel I can see from your package list on the AUR that you don't have the *most* experience maintaining AUR packages, and while I'm not an expert, I'd be happy to help with package maintenance :)

**Comment by taylor85345** [comment]
I was having this issue too, and it was because `paru` wasn't clearing out the old PKGBUILD. Removing `$HOME/.cache/paru/clone/hyprland-git` and trying again resolved the issue in my case.

**Comment by sandervankasteel** [comment]
Good to hear that @taylor85345 isn't the only one that was having this issue. 
I had the same issue with `yay`, so I cleaned it manually and after that the build worked again.

**Comment by ThatOneCalculator** [comment]
> And yes @ElectronicsArchiver I don't have the most experience with maintaining AUR packages, so an extra pair of eyes would be welcoming ;-)

I think you might've done the wrong tag? Either way, feel free to go to https://aur.archlinux.org/pkgbase/hyprland-git/comaintainers and add `that1calculator`

**Comment by ElectronicsArchiver** [comment]
:question: Wait, why am I tagged in this

**Comment by vaxerski** [comment]
sander did an oopsie and tagged u instead of that2calculator

**Comment by ThatOneCalculator** [comment]
As I'm now a maintainer, I'll be fixeying this asap

**Comment by vaxerski** [comment]
they fixed yet? @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
Sorry, I got sick irl so I'm out of commission for a while. First thing I'll do once I'm better.

**Comment by ThatOneCalculator** [comment]
Should be all good now! Please send me a ping if there are any problems :)
