### ISSUE TITLE
bug xkb_options

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#52]
i have multiple keyboard layouts
and i can't switch between them how it is defined in `kb_optiions`
but if will set only `russian` layout it will apply russian layout
so my suggestion, that `kb_options` not working properly, or maybe i'm setting it wrong

part of my config:
```
input {
    kb_layout=us,ru
    # kb_model=
    kb_options=grp:alt_shift_toggle
    # kb_rules=evdev
    follow_mouse=1
}
```

Thank you!

**Comment by vaxerski** [comment]
I don't know, never used multiple layouts. Chances are though, that switching layouts was handled by Xorg on X, and Hyprland does not handle that. If that's the case, I can add in support for switchable layouts.

**Comment by vaxerski** [comment]
You can try handling that via `hyprctl`

example:

```
bind=SUPER,R,exec,hyprctl keyword input:kb_layout ru
```
et cetera.

It should work, let me know if it does.

**Comment by vaxerski** [comment]
fixed above in 15eb844260965dfeeddf9a684e00175bac62ee9b
now works as intended. Be aware that changing your keymap changes the keybinds!
![20220422_14h12m08s_grim](https://user-images.githubusercontent.com/43317083/164712087-79a84804-3dc1-42a1-a054-1a97b36aa1ca.png)
![20220422_14h12m21s_grim](https://user-images.githubusercontent.com/43317083/164712099-582496b7-e527-44ba-a5cd-ffd5a1e74e8a.png)

**Comment by fedoranvar** [comment]
i'll try it.
though it's a bit hacky way, and still  `kb_options` doesn't work well. ( in `wayfire` thihs option works) .

in  spare time, i'll try to look up how `wayfire` handles it

Thank you!

**Comment by Vertecedoc4545** [comment]
maybe is possible to use the sway implementation that works just fine

**Comment by fedoranvar** [comment]
with recent commit `ff86f723` i can confirm that bug has been resolved.

that is good!

thank you!
