### ISSUE TITLE
hyprctl workspaces names and percentages in rules

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#53]
Good day to you!

few suggestions:

1. Displayin workspace's names in `hyprctl workspaces` and `hyprctl monitors` - could be useful for information bars
![image](https://user-images.githubusercontent.com/52028706/164526886-593237a7-e9f6-4b00-8109-592fe70e734d.png)
![image](https://user-images.githubusercontent.com/52028706/164526927-de5327ad-22e2-4509-888b-bbbd497ff8b8.png)

2. Ability to use percentage values in `move`, `size` rules - so we could align (snap) windows, regarding different monitors resolutions 

(example:  powermenu, launchher  etc. in terminal)
![image](https://user-images.githubusercontent.com/52028706/164527252-6db3f598-0403-49ca-b909-ec2ff80591cb.png)

3. Setting opacity by rule

Thank you!

**Comment by vaxerski** [comment]
> Ability to use percentage values in move, size rules - so we could align (snap) windows, regarding different monitors resolutions

like? what percentage rules?

> Setting opacity by rule

you have active and inactive - you mean additional per-app?

**Comment by vaxerski** [comment]
1. done in 727851d6e2c2b1023fe530ac57e2aba19c87a193

**Comment by fedoranvar** [comment]
ayb> Ability to use percentage values in move, size rules - so we could align (snap) windows, regarding different monitors resolutions

![image](https://user-images.githubusercontent.com/52028706/164611610-3603b1e0-b98c-410f-b8e6-584166411c1a.png)

in example above rules will move apps with class `util` to left corner and resize  to monitor height. 

in first pair, it can be done with absolute values
in second pair - it can be done with percentage values (or , maybe float? [0.0 .. 1.0]

> Setting opacity by rule
yes. similar to that
![image](https://user-images.githubusercontent.com/52028706/164613007-8ca3ad3d-3663-4c03-b126-8a91538d909e.png)

**Comment by vaxerski** [comment]
added opacity in 94811485c9e50eb310d8abf19ab60ea01fc3860d
added %s to move and size in a8e5e9c5587b02f6fbbd9bdff97b3913f32f490f

please remember opacity is a product, meaning active_opacity to 0.5 and windowrule opacity to 0.5 will result in an active window's opacity being 0.25. You are allowed to set individual opacities to values >1, but a product of >1 will cause graphical glitches.

cheers

**Comment by fedoranvar** [comment]
that is good.

Thank you !
