### ISSUE TITLE
Either a bug or I'm just ignorant. Workspaces on waybar

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#54]
Workpsaces do not appear on waybar. I already tried Hyprland/workspaces, hyprland/workspaces, and wlr/workspaces in the config file. 

Also, how do I add a windowrule to set a window to ignore the transparency and blur setting? I saw the example windowrules, and decided you were more immature then I thought.

**Comment by vaxerski** [comment]
thanks for the "you were more immature than i thought" line.

workspaces do not appear on waybar? launch from a terminal and notice that big-ass red error that the module was not found. Compile waybar manually with the `HAVE_WLR` and `EXPERIMENTAL` flags. If you don't know how to add them, just define them in the factory header.

windowrules to ignore opacity and blur do not exist yet.

**Comment by niwheeler07** [comment]
sounds good

**Comment by niwheeler07** [comment]
I'm struggling to edit the file correctly, could you point me in the right direction? I know this isn't a hyprland issue, but I'd really appreciate it.

**Comment by vaxerski** [comment]
factory.hpp

**Comment by VaughnValle** [comment]
@niwheeler07 Did you make waybar workspaces work? Built waybar with the needed flags but when using wlr/workspaces the modules is just empty in waybar. No errors on cli either about the workspace module missing

**Comment by niwheeler07** [comment]
I have to switch workspaces before they will show up. Just to clarify, you put 
#define HAVE_WLR
#define USE_EXPERIMENTAL
in your factory.hpp file (in the git repo) before compiling?

**Comment by vaxerski** [comment]
> I have to switch workspaces before they will show up. 

thats how the protocol works. waybar cant record certain default workspaces because they're init'd a bit too early. switch away from it (so that it gets deleted, so no windows on it) and back.

> Also on my machine the workspace data shown on waybar is only accurate as to how many workspaces there are

correct. no idea why, i'll look into waybar, but hyprland does emit which workspace is active.

**Comment by niwheeler07** [comment]
Cool, thanks!

**Comment by vaxerski** [comment]
> I have to switch workspaces before they will show up.

fixed now

> Also on my machine the workspace data shown on waybar is only accurate as to how many workspaces there are

seems like a waybar issue, however I couldn't see anything wrong either on mine or on their side. will look more into it later

**Comment by niwheeler07** [comment]
Hate to bother ya again, but is it possible to prevent workspaces being deleted when there are no windows on them and they are not focused?

**Comment by vaxerski** [comment]
not possible.

**Comment by niwheeler07** [comment]
ok

**Comment by vaxerski** [comment]
active workspaces use the style `#workspaces button.active` in waybar. Closing.
