### ISSUE TITLE
Window created animation; enhancing rules; scratchpad

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#57]
Good day to you!

Please, share your thoughts about:

1. created|closed window animation (slide top|bottom|left|right, fade in|out, zoom in|out)
so for example if i have window aligned to left side, i would give `slide right` on creation, and `slide left` on closing, or maybe `quake` terminal effect (`slide bottom|top`)

2. conditional, event, regex rules: 
ability to create conditional rules on event:
events: `created` , `closed`, `fullscreen`, etc.
conditions: like, `if` , `and`, `or`, `then`, `else`
regex: ability to use regex in `app_iid` (class)

3. scratchpad: 
i saw something in `sway`. ability to toggle window/process (chat,terminal, etc.) on any workspace

**Comment by vaxerski** [comment]
1. not atm but planned for the future, ja

2. rules on event - maybe
 
regex for class already supported, use the C++ regex style

3. planned for the future

**Comment by vaxerski** [comment]
1. not atm but planned for the future, ja

2. rules on event - maybe
 
regex for class already supported, use the C++ regex style

conditional - what? if what? if name? there's already a class field

3. planned for the future

**Comment by vaxerski** [comment]
number 1 added in 694f4433a2b6083cef5a4f43e974f9c70b9857af

that's my implementation of it, and it's probably here to stay.

I might add more styles in the future.

**Comment by fedoranvar** [comment]
good. 


i've read the wiki and tried an example for windows
![image](https://user-images.githubusercontent.com/52028706/168444212-30ed6288-f274-484a-8a2c-590109c006f6.png)

but i can't configure animation for sliding, iit still uses default zooming from center

maybe i missing something?

**Comment by vaxerski** [comment]
```
animation=windows,1,10,default,slide
```
the wiki entry is a bit misleading yea, the 4th param is the CURVE, and the 5th is STYLE

**Comment by fedoranvar** [comment]
got it worked.

is there any plans for applying animation with rules?

```bash
windowrules=animation slide <top/right/bottom/left>, util
```

**Comment by vaxerski** [comment]
maybe. unsure yet.

**Comment by vaxerski** [comment]
added window animation rules in d7ad80e6a2ee25bdc524c0012937d73725f5ad2f

see the wiki for more info.

example:
```
windowrule=animation slide right,kitty
```

**Comment by fedoranvar** [comment]
tried window animation rules.
it is good

**Comment by fedoranvar** [comment]
close for extracting scratchpad as separate issue
#114
