### ISSUE TITLE
Output (monitor) navigation

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#60]
Good day to you !

suggesting navigation (or moving windows) between outputs by direction, or by name:
like 

```bash
bind=SUPER,H,focusmonitor,l
bind=SUPER,J,focusmonitor,d
bind=SUPER,K,focusmonitor,u
bind=SUPER,L,focusmonitor,r

bind=SUPER,H,movewindowmonitor,l
bind=SUPER,J,movewindowmonitor,d
bind=SUPER,K,movewindowmonitor,u
bind=SUPER,L,movewindowmonitor,r

bind=SUPER,F1,focusmonitor,name:DVI-I-1
```

thank you!

**Comment by vaxerski** [comment]
added in 500cbd135f3c928f1b16c13bc5a9f39c966127b5 and 8bb908a8da3be119cc64552d4fe8a23cdfb938b8

Not exactly the same wording as you did though, consult the dispatchers list in the wiki.

**Comment by fedoranvar** [comment]
that is good!

thank you!
