### ISSUE TITLE
Suggestion: ability to use external monitor configuration

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#62]
Good day to you!

suggestion for abillity, to use for rearranging monitor's with external utilities, like `kanshi`
at the moment there's no changes after launching `kanshi`  or applying settings in `wdisplays`

Thank you!

**Comment by vaxerski** [comment]
check please if works with 034192650f8194a8720e88070a7287b3f0523ba4

**Comment by fedoranvar** [comment]
didn't worked out.

i've commented all `monitor=` settings in config, and added `exec-once=kanshi`  - `kanshi` and `wdisplays` still didn't worked

**Comment by vaxerski** [comment]
you dont need to comment out anything. Make sure `kanshi` and whatever is launched AFTER the displays are initialized (recommend to put in a "late launch")

Also please remember that `kanshi` and stuff changes are NOT permanent and will be overwritten by the config if reloaded.

**Comment by fedoranvar** [comment]
got it. removed `exec-once=kanshi` and launched `kanshi` later - it worked.

but `wdisplays` still doesn't apply settings. nevertheless, i think issue is resolved
