### ISSUE TITLE
Natural/Inverted scrolling :3?

### ISSUE THREAD

**Issue by delnyn** [vaxerski/Hyprland#63]
hey I was wondering if it would be possible to implement a natural/inverted scrolling thing

**Comment by vaxerski** [comment]
afaik its just a libinput thing - so yea

**Comment by delnyn** [comment]
oh shit sry

**Comment by vaxerski** [comment]
what i meant was "wait 5 mins i'll add it"

**Comment by delnyn** [comment]
oh wait no maybe uh

**Comment by delnyn** [comment]
yeah lol misunderstanding but you're right it's doable through my libinput config

**Comment by vaxerski** [comment]
added natural scrolling into config just now, inverted scroll should be in the libinput stuf

**Comment by delnyn** [comment]
thanks a looot

**Comment by fufexan** [comment]
Can per-mouse/touchpad inverted scrolling also be implemented? I found no way of configuring libinput on Wayland.

**Comment by vaxerski** [comment]
you found no way because there is no way. Yes, can do.
