### ISSUE TITLE
Suggestion: Titles in grouped windows

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#65]
Good day to you!

suggesting to add titles of grouped windows to be able to distinguish them from ordinary windows.(e.g. similar to sway)
![image](https://user-images.githubusercontent.com/52028706/167309331-a408ffad-9333-41fb-9344-6d3498aa81c5.png)

Thank you!

**Comment by vaxerski** [comment]
Maybe later, I don't know how efficient rendering text with cairo would be here. It's a cosmetic one anyways.

**Comment by fedoranvar** [comment]
maybe for start some indication can be implemented or something that can distinguish groupped windows from ordinary?

**Comment by vaxerski** [comment]
All of this will be added once I get to work on the window decorations interface.

**Comment by vaxerski** [comment]
Added in bdf1c1619529792e95cd6cf2aa1d68e51db76252

Very basic for now, look like this:
![20220528_20h46m37s_grim](https://user-images.githubusercontent.com/43317083/170838939-2e1b4e49-bd53-42f9-8aa7-ad448f60a110.png)

I might add text to them in the footore.

**Comment by fedoranvar** [comment]
it works good.

If you want, you can close this issue

**Comment by vaxerski** [comment]
I will close it. Titles might be added in the future, but they have a quite substantial impact on the performance from my experience, so it might be up to debate.
