### ISSUE TITLE
Suggestion: implementing virtual pointer protocol

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#67]
Good day to you!

i was  trying to run `warpd` (https://github.com/rvaiya/warpd) , but received message something like `Couldn't init virtual pointer (is it implemented?)`

as i understand it looks for `virtual pointer protocol`.
What's your suggestions?

Thank you!

**Comment by vaxerski** [comment]
I don't know what in the actual f that is but yeah I can implement that.

**Comment by fedoranvar** [comment]
thank you!

basically, `warpd` for controlling cursor with keyboard

**Comment by vaxerski** [comment]
added in d438bd970a621db7e158936459922f8165ccee78

I've had it work flawlessly on single-mon, but would crash for me on multimon on exit. Seems like some weird layer surface shenaningans. Might be connected to the fact Hyprland does not respect subsurfaces on layers. Should do that.

Anyways, if crashing on exit, that's a separate issue. If it happens to everyone and not just me, open a separate issue.

**Comment by fedoranvar** [comment]
tried `warpd`
it launches works with different modes, but when i'm trying to navigate with `hjkl`, cursor fly away in that direction

**Comment by vaxerski** [comment]
no clue, maybe lost focus

**Comment by vaxerski** [comment]
possibly the virt cursor is triggering a mouse move event which focuses the window below. That's just how hyprland works, though.

**Comment by vaxerski** [comment]
> possibly the virt cursor is triggering a mouse move event which focuses the window below. That's just how hyprland works, though.

exactly the same reason as stated above.

**Comment by fedoranvar** [comment]
i think you're right

i tested it on empty screen and virtual pointer works fine, and also noticed triggered mouse move.
there is no way to separate them? like, move mouse to position where virtual pointer was destroyed?

**Comment by vaxerski** [comment]
how would the user signify they want an unfocus?

**Comment by fedoranvar** [comment]
maybe adding dispatcher `unfocus`?

**Comment by vaxerski** [comment]
uhh very hacky

**Comment by fedoranvar** [comment]
maybe for beginning just adding dispatcher?

i will test and tell more information/

also noticed: at startup virtualpointer and cursor are in different positions and they move with different speed, shjouldn't mouse follow virtual pointer?

**Comment by fedoranvar** [comment]
tested virtual pointer on `sway`:

*  in virtual pointer mode windows not focusing (even if i have `focus_follow_mouse  yes` in config)
* mouse cursor follow virtual pointer, so:
* when virtual pointer destroyed mouse cursor appears on last place

**Comment by vaxerski** [comment]
check with ad66c158ba793c424519eaee0a64fb81860f5e3c

**Comment by fedoranvar** [comment]
yes, it works good
now mouse cursor doesn't fly away,

but  i can't manipulate with windows by virt. pointer, like (`left/right click`, drag)
![image](https://user-images.githubusercontent.com/52028706/178389835-d8a8cec1-c430-4777-8397-df69e4eb87b4.png)

and mouse cursor doesn't follow exact position of virt pointer, so by destroying virt pointer cursor in some offset
(dot - is virt pointer, circle - mouse cursor)
![image](https://user-images.githubusercontent.com/52028706/178390459-8d844058-ef7b-4954-b872-c9588221c26c.png)
