### ISSUE TITLE
Crash: Underflow in removeBeginEndSpacesTabs(): Assertion '__pos <= size()' failed.

### ISSUE THREAD

**Issue by mdartmann** [vaxerski/Hyprland#68]
**Describe the bug**
After compiling the latest commit of Hyprland on my system and trying to start it, Hyprland crashes with the following message:
`/usr/include/c++/12.1.0/bits/basic_string.h:1221: constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.`

This happens both with the auto-generated config file and the example provided in the repository.
After running it through gdb, the following loop in the `removeBeginEndSpacesTabs()` function seems to be the issue:
```cxx
while (str[str.length() - 1] == ' ' || str[str.length() - 1] == '\t') {
        str = str.substr(0, str.length() - 1);
    }
```
It looks like `substr()` is underflowing here (the value of `__pos` is `numeric_limits(size_t)::max()`:

```gdb
in std::__cxx11::basic_string, std::allocator >::operator[](unsigned long) (__pos=18446744073709551615, this=0x7fff697f9370) at /usr/include/c++/12.1.0/bits/basic_string.h:1221
```
**Images/videos/anything that would help**

<details><summary>GDB backtrace</summary><pre>
Thread 40 "Hyprland" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff697fa640 (LWP 5885)]
0x00007ffff7602a6c in pthread_kill () from /usr/lib/libc.so.6
(gdb) set pagination off
(gdb) bt
#0  0x00007ffff7602a6c in pthread_kill () at /usr/lib/libc.so.6
#1  0x00007ffff75ab048 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff758f0f4 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff78e7a0e in  () at /usr/lib/libstdc++.so.6
#4  0x00000000004648c1 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long) (__pos=18446744073709551615, this=0x7fff697f9370) at /usr/include/c++/12.1.0/bits/basic_string.h:1221
#5  removeBeginEndSpacesTabs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (str=...) at /home/mae/dev/git/Hyprland/src/helpers/MiscFunctions.cpp:72
#6  0x00000000004325e1 in CConfigManager::parseLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (this=0xd6f170, line=<optimized out>) at /home/mae/dev/git/Hyprland/src/config/ConfigManager.cpp:438
#7  0x000000000043324f in CConfigManager::loadConfigLoadVars() (this=0xd6f170) at /home/mae/dev/git/Hyprland/src/config/ConfigManager.cpp:490
#8  0x0000000000433e6c in CConfigManager::init() (this=0xd6f170) at /home/mae/dev/git/Hyprland/src/config/ConfigManager.cpp:78
#9  0x000000000047efaa in CThreadManager::handle() (this=<optimized out>) at /home/mae/dev/git/Hyprland/src/managers/ThreadManager.cpp:21
#10 0x000000000047f127 in operator() (__closure=<optimized out>) at /home/mae/dev/git/Hyprland/src/managers/ThreadManager.cpp:7
#11 std::__invoke_impl<void, CThreadManager::CThreadManager()::<lambda()> > (__f=<optimized out>) at /usr/include/c++/12.1.0/bits/invoke.h:61
#12 std::__invoke<CThreadManager::CThreadManager()::<lambda()> > (__fn=<optimized out>) at /usr/include/c++/12.1.0/bits/invoke.h:96
#13 std::thread::_Invoker<std::tuple<CThreadManager::CThreadManager()::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/12.1.0/bits/std_thread.h:252
#14 std::thread::_Invoker<std::tuple<CThreadManager::CThreadManager()::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/12.1.0/bits/std_thread.h:259
#15 std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThreadManager::CThreadManager()::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/12.1.0/bits/std_thread.h:210
#16 0x00007ffff78eca43 in  () at /usr/lib/libstdc++.so.6
#17 0x00007ffff7600afa in  () at /usr/lib/libc.so.6
#18 0x00007ffff7687930 in  () at /usr/lib/libc.so.6
</pre></details>
<details><summary><code>/tmp/hypr/hyprlandd.log</code></summary><pre>
[LOG] Hyprland init finished.
[LOG] Creating the CHyprError!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 200 points, mem usage: 0.80kB, time to bake: 33.88µs. Estimated average calc time: 0.24µs.
[LOG] Creating the ConfigManager!
[LOG] Creating the ThreadManager!
[LOG] Creating the InputManager!
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 200 points, mem usage: 0.80kB, time to bake: 13.34µs. Estimated average calc time: 0.20µs.
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 3.2 Mesa 22.0.3
[LOG] Vendor: AMD
[LOG] Renderer: AMD RENOIR (LLVM 13.0.0, DRM 3.46, 5.18.0-rc5)
[LOG] Supported extensions size: 145
</pre></details>

<details><summary><code>coredumpctl info</code></summary><pre>
           PID: 6550 (Hyprland)
           UID: 1001 (mae)
           GID: 1001 (mae)
        Signal: 6 (ABRT)
     Timestamp: Thu 2022-05-12 02:20:52 CEST (10s ago)
  Command Line: build/Hyprland
    Executable: /home/mae/dev/git/Hyprland/build/Hyprland
 Control Group: /user.slice/user-1001.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1001.slice
       Session: 2
     Owner UID: 1001 (mae)
       Boot ID: 09ff13ea36fa4a84b17e81105c2f43f3
    Machine ID: cec22b793c424a6fbbf60d89ff248812
      Hostname: brainblast
       Storage: /var/lib/systemd/coredump/core.Hyprland.1001.09ff13ea36fa4a84b17e81105c2f43f3.6550.1652314852000000.zst (present)
     Disk Size: 2.1M
       Message: Process 6550 (Hyprland) of user 1001 dumped core.
                
                Module /home/mae/dev/git/Hyprland/build/Hyprland with build-id d85a85b31ba5cf6a7e98c2db5c7966b804801259
                Module linux-vdso.so.1 with build-id c809e6eacfc4b47d8a822707746fd75ca7a546b6
                Module libicudata.so.71 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                Module libicuuc.so.71 with build-id 443efaeecd90c3892d66db2842faacf8655002b7
                Module libxml2.so.2 with build-id cb13b1751f75c41d23c5d0e8c950e0e022c4c9e1
                Module libncursesw.so.6 with build-id c89348a28e3b095bb77c87308e939491b7495996
                Module libedit.so.0 with build-id d2e14c6aaea17ba5281064719c286e2e6ef779b8
                Module libdrm_nouveau.so.2 with build-id e68fbb7ef7ad19b715273b5032bdbc2d4b89f966
                Module libdrm_amdgpu.so.1 with build-id 0e2484f17f6ac61d1a867aa5935a47af32b61bb5
                Module libelf.so.1 with build-id 7519d61f4328d3e76b55d697277da5bce8fead5b
                Module libdrm_radeon.so.1 with build-id 5afcb4b693e350a0519d5471652840ddfd0d2e34
                Module libsensors.so.5 with build-id 4a0e702ad6ee57fb163f5e349602f1532160ba0d
                Module libLLVM-13.so with build-id 19ae3952f3a275ffd1433d9d29c52e7ef2748d03
                Module radeonsi_dri.so with build-id cf55aa3b1f094cf5698a474dc928ab4af7f3ee0f
                Module libgpg-error.so.0 with build-id 9f90d75d06bb05d5810e00db5957635d6c0e731d
                Module libpcre.so.1 with build-id 1ef380442cd80ba53c17f594bf71e46a9bc71504
                Module libbrotlicommon.so.1 with build-id 00d072f6454e4b7bc94887ed386f7cc6674a4386
                Module libgcrypt.so.20 with build-id 56b88d997547f8aeda6c2695a14b36fdfb5077df
                Module libcap.so.2 with build-id 402c3d7bdc5cf8a476b5e896cf69a573cbc52a16
                Module liblz4.so.1 with build-id 765cc1b48ddfe3c243a02a3ba78c069a429dde6e
                Module libzstd.so.1 with build-id 5ec0bfb04a6444d46d0a58a9854100c43a7098c4
                Module liblzma.so.5 with build-id f75cb73a14d92050282b68e4b506d003d1b5a6a2
                Module libglib-2.0.so.0 with build-id aa19f5d5c8cc53d93970579278af26f10b64c88c
                Module libgobject-2.0.so.0 with build-id 782ee15870818a1563a885f7d800681aa4d729d9
                Module libgudev-1.0.so.0 with build-id 9e08d7427e5423099f6ee5c3d899f2edc8e5f05b
                Module libbrotlidec.so.1 with build-id 4fab86cf632a85f978072500ac1af0db31e29c0d
                Module libbz2.so.1.0 with build-id 6bea02078f9f968a9ad1bb1afe808c6fc2af3aa9
                Module libsystemd.so.0 with build-id 64e578584a71447f251a7c98438e20fa06927ab7
                Module libXdmcp.so.6 with build-id e6395377b204a0a72fe8f4fe98f57c30d0cf663d
                Module libXau.so.6 with build-id 3a4fe7a74783f638391b67b84dfa45e762ad3249
                Module libwacom.so.9 with build-id 91bcd3cde8865fcbaa7684a46a50a0e1073facfb
                Module libevdev.so.2 with build-id a13ea05733a4e6e923b5a4f64390f55fc9e58a35
                Module libmtdev.so.1 with build-id 15a112a015f438fad749a64ee8dc4fca356d21e6
                Module libXrender.so.1 with build-id c2feffa0740f12728d3a9e5bdeda1c62018c7d86
                Module libfreetype.so.6 with build-id 5bba53960697069454cba35cfdca80245f41ed67
                Module libfontconfig.so.1 with build-id 4b9026746624c68a7e63d1c48b45995be480145b
                Module libpng16.so.16 with build-id 722a4603a3ca168a8447ea42bcf0e275c8acf464
                Module libz.so.1 with build-id 04edd07c3218aad4a84cfae6d402b3e598eeb344
                Module libffi.so.8 with build-id b5e027e9d3f9e6740a59ee3c87dee9621bd28b5a
                Module libxshmfence.so.1 with build-id c619c0833d6c1545a393fe9fee25a41e5c71532d
                Module libxcb-sync.so.1 with build-id 6b383125f6c0eab05ee59b15fd49beb295e1d6ce
                Module libexpat.so.1 with build-id a0700866351e508bf3ea61b8628fa1d1e108cf61
                Module libXxf86vm.so.1 with build-id 9992f3f013f0800351b47ec355be6de1159eb2ba
                Module libXfixes.so.3 with build-id 8d1271204bd1a6e24fcf70cefe65692a9e8ba17e
                Module libXext.so.6 with build-id dfaff5070d649a0b1e21eb804ab59bff083021ec
                Module libxcb-dri2.so.0 with build-id 52e3e629dddbc43769296663df9d1baa5a349755
                Module libX11-xcb.so.1 with build-id a250384ca88bed9282ef6cbe8730692196b1fe65
                Module libxcb-glx.so.0 with build-id 51f8a855ca2735c27be06711efa2cd2ecacf161b
                Module libX11.so.6 with build-id 9306719e146b370949a1a47089300aeabad2f54f
                Module libglapi.so.0 with build-id bb4a3a6fcc14250a5ea724e7978f0c2471f99345
                Module ld-linux-x86-64.so.2 with build-id 4b9df90bffe68a08d98b3f085789fa8f4bc2b3d3
                Module libxcb-errors.so.0 with build-id 468ae11dc2ca0db580b900dc7e813e5cbe567b7a
                Module libxcb-res.so.0 with build-id 75a76049c03f5a6c18ea40d68527fc400da9b092
                Module libxcb-icccm.so.4 with build-id 6588b39c32b466fb775861358001be7c60832511
                Module libxcb-composite.so.0 with build-id fac58b2ad754009f902a87d9e4aa35fce9004122
                Module libseat.so.1 with build-id fe44590fc30eae760ff5f03916f8f34cf2893c6a
                Module libwayland-client.so.0 with build-id c5e337187c941a9b173bab487ab45b7b74571977
                Module libxcb-xinput.so.0 with build-id 7a623723f868549a239aea2c66c382375a1c21fc
                Module libxcb-xfixes.so.0 with build-id 42fc13fd396a3dc935d3eae71100e1eeb27cf5cb
                Module libxcb-shm.so.0 with build-id d49f4ad5b933d7af8454afe7c12a7c298a049c6c
                Module libxcb-render-util.so.0 with build-id a9400137ad1ea30ff7b409eb7d68be596868073e
                Module libxcb-render.so.0 with build-id 721f4945fcb2c1cedfb953d89a82a8555548b63f
                Module libxcb-present.so.0 with build-id 251667a39b1fa20fd4d989662584369fbe7f73fa
                Module libxcb-dri3.so.0 with build-id f5325bdbe6b4a051a04c3f49155e8b5e423d59aa
                Module libvulkan.so.1 with build-id d85e397a830b65894feeb1bbd8ff6a26bd17bd01
                Module libGLESv2.so.2 with build-id d355cdf6a9743b59de27e47f7605d2dfc743ce2e
                Module libudev.so.1 with build-id 0a7761682e6a6989d5c64b86cb8ab9da7934dd3e
                Module libgbm.so.1 with build-id 2bc5f15d50f0dde8650273f5cd98f93a2d2253e8
                Module libdrm.so.2 with build-id f71c59fdef505c6a2c266281e1afef7317d3f820
                Module libc.so.6 with build-id 1495657d84660daa6a52a8c5020954a26b715f2a
                Module libgcc_s.so.1 with build-id 659122bc0be96cfeb55ebeb4a71a90d92ab37141
                Module libm.so.6 with build-id b4449b3a0495863b3f5481d12d5f481dd8a73e83
                Module libstdc++.so.6 with build-id 6e8d776f78748fdfd9aba99245f73f006bb542dc
                Module libxcb.so.1 with build-id e397018b6a4aee7b4590072cad6d88f84b269225
                Module libinput.so.10 with build-id 694fd8072fdc7bcf671023e9378fbb703aad5c00
                Module libxkbcommon.so.0 with build-id 5bd0384ab7484d2900c6daa7ae04cf7d0e4317ff
                Module libEGL.so.1 with build-id 72523f0768161017d9d8826464a43016fdabbeb8
                Module libcairo.so.2 with build-id 8294727fa097bd71981ae8349a399149216a9b8b
                Module libwayland-server.so.0 with build-id 57de61eb3a883e8d3730006f838ab88fd34dec0a
                Module libGL.so.1 with build-id 7bd637d35e77261dd6693cbdc79a62a17d37738a
                Module libpixman-1.so.0 with build-id 2668e3edffcd6a8ff1a4e3c7855fcd2b63af1eed
                Module libwlroots.so.11 with build-id 848d1ae63834f3a5a85fef3cf62591d403d0bc86
                Stack trace of thread 6590:
                #0  0x00007f8afae02a6c pthread_kill (libc.so.6 + 0x9fa6c)
                #1  0x00007f8afadab048 raise (libc.so.6 + 0x48048)
                #2  0x00007f8afad8f0f4 abort (libc.so.6 + 0x2c0f4)
                #3  0x00007f8afb0e7a0e _ZSt21__glibcxx_assert_failPKciS0_S0_ (libstdc++.so.6 + 0xe7a0e)
                #4  0x00000000004648c1 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x648c1)
                #5  0x00000000004325e1 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x325e1)
                #6  0x000000000043324f n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x3324f)
                #7  0x0000000000433e6c n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x33e6c)
                #8  0x000000000047efaa n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x7efaa)
                #9  0x000000000047f127 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x7f127)
                #10 0x00007f8afb0eca43 n/a (libstdc++.so.6 + 0xeca43)
                #11 0x00007f8afae00afa n/a (libc.so.6 + 0x9dafa)
                #12 0x00007f8afae87930 n/a (libc.so.6 + 0x124930)
                
                Stack trace of thread 6553:
                #0  0x00007f8afadfd147 n/a (libc.so.6 + 0x9a147)
                #1  0x00007f8afadffad2 pthread_cond_wait (libc.so.6 + 0x9cad2)
                #2  0x00007f8af80c0cec n/a (radeonsi_dri.so + 0xc0cec)
                #3  0x00007f8af80c0a8c n/a (radeonsi_dri.so + 0xc0a8c)
                #4  0x00007f8afae00afa n/a (libc.so.6 + 0x9dafa)
                #5  0x00007f8afae87930 n/a (libc.so.6 + 0x124930)
                
                Stack trace of thread 6554:
                #0  0x00007f8afadfd147 n/a (libc.so.6 + 0x9a147)
                #1  0x00007f8afadffad2 pthread_cond_wait (libc.so.6 + 0x9cad2)
                #2  0x00007f8af80c0cec n/a (radeonsi_dri.so + 0xc0cec)
                #3  0x00007f8af80c0a8c n/a (radeonsi_dri.so + 0xc0a8c)
                #4  0x00007f8afae00afa n/a (libc.so.6 + 0x9dafa)
                #5  0x00007f8afae87930 n/a (libc.so.6 + 0x124930)
                
                Stack trace of thread 6556:
                #0  0x00007f8af18f4924 _ZN4llvm3ARM20getCanonicalArchNameENS_9StringRefE (libLLVM-13.so + 0xcf4924)
                #1  0x00007f8af19e3b09 n/a (libLLVM-13.so + 0xde3b09)
                #2  0x00007f8af19e70d1 _ZN4llvm6TripleC1ERKNS_5TwineE (libLLVM-13.so + 0xde70d1)
                #3  0x00007f8af1a52438 _ZN4llvm14TargetRegistry12lookupTargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS6_ (libLLVM-13.so + 0xe52438)
                #4  0x00007f8af3bd34d5 LLVMGetTargetFromTriple (libLLVM-13.so + 0x2fd34d5)
                #5  0x00007f8af8d4ef53 n/a (radeonsi_dri.so + 0xd4ef53)
                #6  0x00007f8af8d4f9fa n/a (radeonsi_dri.so + 0xd4f9fa)
                #7  0x00007f8af8c83783 n/a (radeonsi_dri.so + 0xc83783)
                #8  0x00007f8af8cb7d6c n/a (radeonsi_dri.so + 0xcb7d6c)
                #9  0x00007f8af80c0dba n/a (radeonsi_dri.so + 0xc0dba)
                #10 0x00007f8af80c0a8c n/a (radeonsi_dri.so + 0xc0a8c)
                #11 0x00007f8afae00afa n/a (libc.so.6 + 0x9dafa)
                #12 0x00007f8afae87930 n/a (libc.so.6 + 0x124930)
                
                Stack trace of thread 6550:
                #0  0x00007f8af85506d7 n/a (radeonsi_dri.so + 0x5506d7)
                #1  0x000000000048381a n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x8381a)
                #2  0x00000000004888c7 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x888c7)
                #3  0x000000000042783f n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x2783f)
                #4  0x000000000041c7e7 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x1c7e7)
                #5  0x00007f8afad923a0 n/a (libc.so.6 + 0x2f3a0)
                #6  0x00007f8afad92451 __libc_start_main (libc.so.6 + 0x2f451)
                #7  0x0000000000420fe5 n/a (/home/mae/dev/git/Hyprland/build/Hyprland + 0x20fe5)
                ELF object binary architecture: AMD x86-64
</pre></details>

Config file:
<pre>
# This is an example Hyprland config file.
# Syntax is the same as in Hypr, but settings might differ.
#
# Refer to the wiki for more information.

monitor=,1280x720@60,0x0,1
workspace=DP-1,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1
}

general {
    max_fps=60
    sensitivity=0.25
    main_mod=SUPER

    gaps_in=5
    gaps_out=20
    border_size=2
    col.active_border=0x66ee1111
    col.inactive_border=0x66333333

    damage_tracking=monitor # experimental, monitor is 99% fine, but full might have bugs!
}

decoration {
    rounding=10
    blur=1
    blur_size=3 # minimum 3
    blur_passes=2 # minimum 2, more passes = more resource intensive.
    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
}

animations {
    enabled=1
    speed=7 # speed is measured in 100s of ms, 7 = 700ms
    curve=default # you can customize your own bezier curves, see the wiki
    windows_curve=default # specific curve for all window animations
    windows_speed=6 # specific speeds for components can be made with name_speed=float. 0 means use global (speed=float). If not set, will use the global value.
    windows=1
    borders=1
    borders_speed=20
    fadein=1 # fade in AND out
    fadein_speed=20
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

# example window rules
# for windows named/classed as abc and xyz
windowrule=move 69 420,abc
windowrule=size 420 69,abc
windowrule=tile,xyz
windowrule=float,abc
windowrule=pseudo,abc
windowrule=monitor 0,xyz

# example binds
bind=SUPER,Q,exec,kitty
bind=SUPER,C,killactive,
bind=SUPER,M,exec,pkill Hyprland
bind=SUPER,E,exec,dolphin
bind=SUPER,V,togglefloating,
bind=SUPER,R,exec,wofi --show drun -o DP-3
bind=SUPER,P,pseudo,

bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspace,1
bind=ALT,2,movetoworkspace,2
bind=ALT,3,movetoworkspace,3
bind=ALT,4,movetoworkspace,4
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,6
bind=ALT,7,movetoworkspace,7
bind=ALT,8,movetoworkspace,8
bind=ALT,9,movetoworkspace,9
bind=ALT,0,movetoworkspace,10
</pre>

**Comment by mdartmann** [comment]
This diff appears to fix the for me:

```patch
diff --git a/src/helpers/MiscFunctions.cpp b/src/helpers/MiscFunctions.cpp
index bf8724c..61ae0c4 100644
--- a/src/helpers/MiscFunctions.cpp
+++ b/src/helpers/MiscFunctions.cpp
@@ -69,7 +69,7 @@ std::string removeBeginEndSpacesTabs(std::string str) {
         str = str.substr(1);
     }
 
-    while (str[str.length() - 1] == ' ' || str[str.length() - 1] == '\t') {
+    while (str.length() != 0 && (str[str.length() - 1] == ' ' || str[str.length() - 1] == '\t')) {
         str = str.substr(0, str.length() - 1);
     }
 
```

Let me know if I should open a PR for this or if there's something I'm missing here.

**Comment by vaxerski** [comment]
u can make a pr, weird though as it had never crashed for me. But oh well, stuff happens.
