### ISSUE TITLE
Starting Hyprland from SDDM leads to frozen start up screen

### ISSUE THREAD

**Issue by MNolan147** [vaxerski/Hyprland#71]
When starting from SDDM, it will allow me to start Hyprland but it will get stuck on start up.
I'm running it on an arch virtual machine.

**Comment by vaxerski** [comment]
I am using SDDM too. Are you using the AUR package? It's currently broken. I should mention that in the wiki.

**Comment by MNolan147** [comment]
That would explain it. I am using the AUR packets, so I will try to compile from source and see if that fixes it

**Comment by ThatOneCalculator** [comment]
This issue is now fixed and should be closed, cc @vaxerski @MNolan147

**Comment by vaxerski** [comment]
okay, closing then.
