### ISSUE TITLE
Can't compile the latest version

### ISSUE THREAD

**Issue by Whax** [vaxerski/Hyprland#72]
Hi,

**Describe the bug**
I can't compile the latest version, following the wiki instructions. I'm on Arch, up to date, with all the required dependencies installed

Here is the log
[bug.log](https://github.com/vaxerski/Hyprland/files/8692367/bug.log)

**Comment by vaxerski** [comment]
you're not using `wlroots-git`

**Comment by Whax** [comment]
Nope, I'm using it :x 

```pacman -Qm | grep wlroots-git
wlroots-git 0.16.0.r5481.19896e7f-1
wlroots-git-debug 0.16.0.r5481.19896e7f-1

**Comment by vaxerski** [comment]
huh. maybe they updated. I'll check in a while.

**Comment by Whax** [comment]
No prob, take your time ! Thanks, anyway

**Comment by vaxerski** [comment]
can't reproduce. latest wlroots-git.

These errors are expected if using wlroots-git from like a month ago.

**Comment by Whax** [comment]
Hey,

my yay cache was clean, so this is weird. But I made it working by compiling manually the latest version from https://gitlab.freedesktop.org/wlroots/wlroots.

Issue can be closed. Thanks for your help :)
