### ISSUE TITLE
Hyprland freezes at startup

### ISSUE THREAD

**Issue by sematarygraveman** [vaxerski/Hyprland#73]
When I start Hyprland from SDDM, it just shows the logo and doesn't do anything else besides that I have a mouse to move around. I installed it from the aur. When launching on tty it's just black with a mouse cursor that I can move. I also use an Amd gpu and Arch. 

![image](https://user-images.githubusercontent.com/105575548/168456962-2a657158-0fa2-4ed5-b20a-8a0597cdec9a.png) This is about what it shows

Nothing is in the log, and the coredumpctl is Sat 2022-05-14 22:57:52 CDT  4541 1001 1001 SIGSEGV present  /usr/local/bin/Hyprland .

**Comment by vaxerski** [comment]
the logo is you walllaper, idk use super+q to open kitty?

**Comment by sematarygraveman** [comment]
> the logo is your walllaper, idk use super+q to open kitty?

I tried to do that and nothing happened, same with all other key combinations

**Comment by vaxerski** [comment]
open any other wm/de

launch hyprland (it will open in a window)

hover over it

press some keybinds

do `cat /tmp/hypr/hyprland.log`

does it register your keypresses?

**Comment by sematarygraveman** [comment]
I found the problem. No hyprland.conf generated, so I just created one and pasted the example config, and now it works.
