### ISSUE TITLE
Not be able to install via yay

### ISSUE THREAD

**Issue by peterwilfride** [vaxerski/Hyprland#75]
**Describe the bug**
I make sure if all dependencies are installed and then `yay -S hyprland-git`, but failed.

**Images/videos/anything that would help**
![image](https://user-images.githubusercontent.com/41086317/168482852-d7013417-17d9-43ef-9091-f8c85f0cf603.png)

**Comment by vaxerski** [comment]
thanks for the visible errors...

anyways I don't maintain the packages. Build from source, please.

For AUR, @ThatOneCalculator and @sandervankasteel maintain it.

**Comment by ThatOneCalculator** [comment]
> Subcommand failed

Not sure what this would be about, but I don't think it's an issue with the package. I tried the AUR PKGBUILD on a fresh Arch Linux virtual machine and it worked fine.

**Comment by sandervankasteel** [comment]
@peterwilfride if you can post this as a comment with the log on the AUR package package, I will check it out and see what's going wrong.

**Comment by peterwilfride** [comment]
![image](https://user-images.githubusercontent.com/41086317/168483404-954d639f-17f0-4290-93b5-81a6ed7165a2.png)

I try compile from source and I get the same errors.

@sandervankasteel 
Sorry, how can I get these logs?

**Comment by vaxerski** [comment]
wlroots updated, breaking compat. CI failed. Sec.

**Comment by vaxerski** [comment]
fixed.

**Comment by ThatOneCalculator** [comment]
Imagine blaming my amazing AUR pkgbuild smh 😤😤😤😤😤😤😤

**Comment by vaxerski** [comment]
sorry sorry
