### ISSUE TITLE
Build failed (probably `96cdf8fd`)

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#77]
Good day to you!

i've tried building with `1d4d52af`

but stumbled upon error
![image](https://user-images.githubusercontent.com/52028706/168535786-1e894196-f75c-479e-8d18-887d4a019bda.png)

**Comment by vaxerski** [comment]
no, wlroots-git update. Always keep up to date with wlroots-git.

**Comment by fedoranvar** [comment]
you're right. updated wlroots and its builded

i've been using this repo's flake, it seems it's using "old" wlroots.
