### ISSUE TITLE
Scaling doesnt work

### ISSUE THREAD

**Issue by Magnitudexx** [vaxerski/Hyprland#79]
**Describe the bug**
On a 4K display, I try to run 2x scaling, resulting in the compositor only running in a quarter ofthe screen.

**Images/videos/anything that would help**
I'll try getting one

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8699819/hyprland.log)

**Comment by vaxerski** [comment]
i know. It's on the todo list. It's a real pain in the ass to code in, at least has been for me.

**Comment by Magnitudexx** [comment]
I bet, I realized that I've seen it somewhere else before so I started looking into it but I cannot understand why it does this

**Comment by vaxerski** [comment]
please try the [scaling branch](https://github.com/vaxerski/Hyprland/tree/scaling), notable features not working: damage tracking on full.

**Comment by vaxerski** [comment]
blur fixed

**Comment by vaxerski** [comment]
fadeout fixed

**Comment by Magnitudexx** [comment]
scaling works ok now. Librewolf (fork of firefox) doesn't render fully, leaving a big gap to the border

**Comment by vaxerski** [comment]
yeah, there might be bugs. I need to investigate more.

**Comment by vaxerski** [comment]
fixed (as far as im aware) and recently merged. Report any new bugs separarely.
