### ISSUE TITLE
Not a feature request, a thanks

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#8]
Thank you so much for making this. I was about to ask for it on the hypr repository as a feature request when I saw that it was already in progress. I love c++ (am learning it) and I love hypr and I will definitely use this when it is somewhat more stable. 
If/when I know enough c++ I will definitely contribute to this if it still needs it by then.

THANK YOU SO MUCH!!

**Comment by vaxerski** [comment]
thank you for the kind words :)
