### ISSUE TITLE
Using enter in keybinds?

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [vaxerski/Hyprland#81]
**Describe in detail your idea.**
I can't use KP_Enter when binding something, and I want to bind create terminal to alt+enter

**Comment by vaxerski** [comment]
it was never called enter. It's called RETURN.

**Comment by Aadniz** [comment]
`KP_Enter` is however correct for the numpad enter. And `Return` for the *normal* enter key.
If anyone else come here, just check the `dumpkeys` command.
