### ISSUE TITLE
Dmenu-wl won't launch

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [vaxerski/Hyprland#82]
**Describe the bug**
I know I'm probably just doing something stupid, but setting the run command to `dmenu-wl_run` makes it so that whenever I execute the keybinding(to start the launcher), nothing happens

**Comment by vaxerski** [comment]
dunno, I don't use dmenu. use wofi or bemenu or something

**Comment by ThatOneCalculator** [comment]
@ERROR-404-NULL-NOT-FOUND Appears to be an issue entirely on your end. 

![image](https://user-images.githubusercontent.com/44733677/168730723-ec8e43c2-a6a2-4277-8ea5-4c9e8f4aefba.png)

@vaxerski this issue should be considered invalid.

**Comment by vaxerski** [comment]
okay, closing then.
