### ISSUE TITLE
Crashes, probably gtk-layer-shell related

### ISSUE THREAD

**Issue by TheLastTeapot** [vaxerski/Hyprland#83]
Vlc crashes, chromium crashes, libreoffice crashes, error sent me to gtk-layer-shell, installed that from source and they still crash. Log doesn't help bc it is recreated when I launch hyprland again. Error is an address boundry overflow error.

**Comment by TheLastTeapot** [comment]
cvlc also crashes hyprland, but works in tty

**Comment by vaxerski** [comment]
you haven't posted any coredumps.

VLC:
![20220516_21h20m41s_grim](https://user-images.githubusercontent.com/43317083/168666547-6b1bcc2a-053b-4e2f-932f-ce910d31b12f.png)

LO:
![20220516_21h20m58s_grim](https://user-images.githubusercontent.com/43317083/168666597-7abb8b7e-4d47-4c2c-95d8-c8f08453c243.png)

Chrome:
![20220516_21h21m20s_grim](https://user-images.githubusercontent.com/43317083/168666646-51e2a693-a8fa-46aa-b018-6b0a050a4284.png)

Either you give me coredumps so I can investigate, or I can't do anything.

**Comment by TheLastTeapot** [comment]
that's all the ones that have happened today

**Comment by vaxerski** [comment]
well it's certainly not XDG shell that's wrong, as the crash comes from applying an event to an XWayland window. Something's wrong on your side. This does not seem to be an issue with Hyprland

**Comment by TheLastTeapot** [comment]
yay

**Comment by vaxerski** [comment]
Just recompiled against main upstream and I can confirm both libreoffice and watching dank memes on vlc works as it should. Maybe recompile wlr, update xwayland, recompile hyprland and try again?

**Comment by TheLastTeapot** [comment]
Idk, the only thing that changed before the crashes started happening was updating wlroots-git and hyprland. None of the things you mentioned worked, everything is up to date. If I find a solution I'll put it here.

**Comment by vaxerski** [comment]
if u can pinpoint which commit broke it i can look into it.

```
git reset --hard HASH
```
for resetting.

Furthermore, you can try reducing the xdg protocol ver by editing `Compositor.cpp@70`, change 2 to 1.

**Comment by TheLastTeapot** [comment]
I think the commit was either

https://github.com/vaxerski/Hyprland/commit/e90c1f7022ffd82e463c48260a97850c834f347d
or
https://github.com/vaxerski/Hyprland/commit/50f978e518c83872a25a47b5ddde310ec24ac203

For some reason I did not have xdg-desktop-portal and xdg-desktop-portal-wlr installed, but installing didn't fix it.

**Comment by vaxerski** [comment]
impossible, those do not change anything that could break.

**Comment by TheLastTeapot** [comment]
I had updated hyprland shortly before. In order to try and make hyprland compile, I did a full update for all packages but only like 9 updated. Then I had to update wlroots-git and then I was able to compile those commits.
Clearly it isn't wlroots, so it must be one of those 9.

**Comment by vaxerski** [comment]
I can't help you - I can't reproduce it, and the coredump you provided doesn't seem normal. You complain about XDG, yet the coredump is because of XWayland, besides, it fails in a basically noexcept area.

Unless someone else can attest to this, I'd assume this is an issue on your side.

**Comment by TheLastTeapot** [comment]
Yeah, I'm downgrading all the packages I updated to see if that fixes it. Thanks for being willing to help!

**Comment by TheLastTeapot** [comment]
Downgrading packages did not fix it. I'm not asking for help, I know from my years of pc troubleshooting that it's super annoying when people don't post solutions and things.

**Comment by TheLastTeapot** [comment]
Reinstalled arch and now it works : ]
