### ISSUE TITLE
Change in Wiki

### ISSUE THREAD

**Issue by ThatOneCalculator** [vaxerski/Hyprland#85]
There's something that should be changed under installation.

> # Packages
> **WARNING**: I do not maintain any packages. If they are broken, try building from source first.
> *Arch (AUR)*
> ```
> yay -S hyprland-git
> ```
---
Underneath this blurb, something I recently learned that could be useful can be mentioned by adding the following:
> Given this project is under development and constantly changing, if you want to keep up to date with the latest commits, please consider updating your packages with `yay -Syu --devel`.

**Comment by vaxerski** [comment]
done
