### ISSUE TITLE
VLC media player wonky when in full screen

### ISSUE THREAD

**Issue by Vagahbond** [vaxerski/Hyprland#92]
**Describe the bug**
When in full screen with VLC Media Player, the right click menu works only for a few seconds then hovering it do not do anything. 
Also it's very laggy. 
Also the Play pause and slider for the time do not work at all they're here but clicking them does nothing. I have to exit full screen if I want to do anything and then go back to fullscreen again.

Not a huge bug but I thought useful to make an issue for it.

**Images/videos/anything that would help**
This works:
![1652988757_grim](https://user-images.githubusercontent.com/56230065/169387878-6aa44bf0-f29c-4270-83b0-17b994fd2aad.png)

I cannot screenshot the overlay that gets wonky because it disappears as soon as I use the command to screenshot it.

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8733735/hyprland.log)

**Comment by vaxerski** [comment]
I've came across that.

First, the lag - idk, not an issue with hyprland I think as it's smooth for me.

With the surfaces not being focusable - yeah, I know. I tried to fix it a long time ago but it's so fucking weird.

It would magically work on a windowed session, then stop on a real one. The surfaces are recieving their focus, VLC just decides to ignore it... weird shit. It's LITERALLY only VLC. Any other XWayland or Wayland app works.

> I cannot screenshot the overlay that gets wonky because it disappears as soon as I use the command to screenshot it.
Yeah, the surface loses focus and closes the popup. Slurp (probably what you are using) is a surface too.

So, I am aware of the bug, it is annoying, but it's only VLC that does this and Idfk why. Vivarium has the same issue. Does Sway bug out too?

**Comment by Vagahbond** [comment]
Alright then it's a bug I can live with. 

Sway did not have this issue whatsoever I've been using it for month daily and I never noticed the same issue, so the answer might be in their repository or closed issues.

**Comment by vaxerski** [comment]
alr

**Comment by vaxerski** [comment]
fixed in f522c597efb3ef3efc01fd6fba9a2b4ef4cadbcc ! :D :D :D :D :D

**Comment by vaxerski** [comment]
closing, it's fixed.
