### ISSUE TITLE
Touch pad is not sensitive enoug

### ISSUE THREAD

**Issue by japrogramer** [vaxerski/Hyprland#95]
**Describe the bug**

It takes many passes across the touch pad to move the cursor across the whole screen.

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

**Comment by vaxerski** [comment]
sensitivity...?

**Comment by japrogramer** [comment]
Im accustomed to being able to move from corner to corner of the screen with the touchpad with just one pass, but in Hyprland it takes 4 passes and in weston it only takes one pass.

**Comment by vaxerski** [comment]
yes, there's a sensitivity setting in the config...

**Comment by japrogramer** [comment]
ok, good to know.
