### ISSUE TITLE
exiting out of fullscreen doesnt work, it bugs out from full screen to not fullscreen many times a second

### ISSUE THREAD

**Issue by japrogramer** [vaxerski/Hyprland#97]
**Describe the bug**
So here is what happens when I use `movefocus` to move from a terminal window to firefox
and then try to `fullscreen` with firefox focused the firefox window does go fullscreen but 
when i press the binding for `fullscreen` again instead of going back to not fullscreen 
firefox window glitches from fullscreen and not fullscreen many many times a second

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

**Comment by vaxerski** [comment]
i know, firefox issue. I'll have to find some workaround for it.

**Comment by japrogramer** [comment]
It also happens when going into fullscreen, but don't know exactly how to replicate.
